/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: UInterface.i

package uniset_internal_api

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef _gostring_ swig_type_10;
typedef long long swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef long long swig_type_14;
typedef _gostring_ swig_type_15;
typedef long long swig_type_16;
typedef _gostring_ swig_type_17;
typedef long long swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef long long swig_type_25;
typedef long long swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef long long swig_type_29;
typedef long long swig_type_30;
typedef long long swig_type_31;
typedef long long swig_type_32;
typedef long long swig_type_33;
typedef long long swig_type_34;
typedef long long swig_type_35;
typedef long long swig_type_36;
typedef long long swig_type_37;
typedef long long swig_type_38;
typedef long long swig_type_39;
typedef long long swig_type_40;
typedef long long swig_type_41;
typedef long long swig_type_42;
typedef long long swig_type_43;
typedef long long swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef long long swig_type_47;
typedef _gostring_ swig_type_48;
typedef long long swig_type_49;
typedef _gostring_ swig_type_50;
typedef _gostring_ swig_type_51;
typedef _gostring_ swig_type_52;
typedef _gostring_ swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
typedef _gostring_ swig_type_58;
typedef _gostring_ swig_type_59;
typedef _gostring_ swig_type_60;
typedef _gostring_ swig_type_61;
typedef _gostring_ swig_type_62;
typedef _gostring_ swig_type_63;
typedef _gostring_ swig_type_64;
typedef _gostring_ swig_type_65;
typedef _gostring_ swig_type_66;
typedef _gostring_ swig_type_67;
typedef _gostring_ swig_type_68;
typedef _gostring_ swig_type_69;
typedef _gostring_ swig_type_70;
typedef long long swig_type_71;
typedef long long swig_type_72;
typedef long long swig_type_73;
typedef long long swig_type_74;
typedef long long swig_type_75;
typedef long long swig_type_76;
typedef long long swig_type_77;
typedef long long swig_type_78;
typedef long long swig_type_79;
typedef long long swig_type_80;
typedef long long swig_type_81;
extern void _wrap_Swig_free_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_uniset_init_params_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_1 arg2);
extern uintptr_t _wrap_uniset_init_uniset_internal_api_576c1e11c33cb6aa(swig_intgo arg1, swig_voidp arg2, swig_type_2 arg3);
extern uintptr_t _wrap_getValue_uniset_internal_api_576c1e11c33cb6aa(swig_type_3 arg1);
extern uintptr_t _wrap_setValue__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(swig_type_4 arg1, swig_type_5 arg2, swig_type_6 arg3);
extern uintptr_t _wrap_setValue__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_7 arg1, swig_type_8 arg2);
extern swig_type_9 _wrap_getSensorID_uniset_internal_api_576c1e11c33cb6aa(swig_type_10 arg1);
extern swig_type_11 _wrap_getObjectID_uniset_internal_api_576c1e11c33cb6aa(swig_type_12 arg1);
extern swig_type_13 _wrap_getShortName_uniset_internal_api_576c1e11c33cb6aa(swig_type_14 arg1);
extern swig_type_15 _wrap_getName_uniset_internal_api_576c1e11c33cb6aa(swig_type_16 arg1);
extern swig_type_17 _wrap_getTextName_uniset_internal_api_576c1e11c33cb6aa(swig_type_18 arg1);
extern swig_type_19 _wrap_getConfFileName_uniset_internal_api_576c1e11c33cb6aa(void);
extern swig_type_20 _wrap_getConfigParamsByName__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(swig_type_21 arg1, swig_type_22 arg2);
extern swig_type_23 _wrap_getConfigParamsByName__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_24 arg1);
extern swig_type_25 _wrap_DefaultID_get_uniset_internal_api_576c1e11c33cb6aa(void);
extern swig_type_26 _wrap_DefaultSupplerID_get_uniset_internal_api_576c1e11c33cb6aa(void);
extern swig_intgo _wrap_Params_max_Params_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_Params_uniset_internal_api_576c1e11c33cb6aa(void);
extern _Bool _wrap_Params_add_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_27 arg2);
extern _Bool _wrap_Params_add_str_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_28 arg2);
extern void _wrap_Params_argc_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Params_argc_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_Params_argv_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Params_argv_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_Params_inst_uniset_internal_api_576c1e11c33cb6aa(void);
extern void _wrap_delete_Params_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_id_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_29 arg2);
extern swig_type_30 _wrap_ShortIOInfo_id_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_value_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_31 arg2);
extern swig_type_32 _wrap_ShortIOInfo_value_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_tv_sec_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_33 arg2);
extern swig_type_34 _wrap_ShortIOInfo_tv_sec_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_tv_nsec_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_35 arg2);
extern swig_type_36 _wrap_ShortIOInfo_tv_nsec_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_supplier_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_37 arg2);
extern swig_type_38 _wrap_ShortIOInfo_supplier_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_consumer_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_39 arg2);
extern swig_type_40 _wrap_ShortIOInfo_consumer_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ShortIOInfo_node_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_41 arg2);
extern swig_type_42 _wrap_ShortIOInfo_node_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_ShortIOInfo_uniset_internal_api_576c1e11c33cb6aa(void);
extern void _wrap_delete_ShortIOInfo_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultIO_sinfo_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ResultIO_sinfo_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultIO_ok_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_ResultIO_ok_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_ResultIO__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, _Bool arg2);
extern uintptr_t _wrap_new_ResultIO__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(void);
extern void _wrap_delete_ResultIO_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultValue_value_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_43 arg2);
extern swig_type_44 _wrap_ResultValue_value_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultValue_ok_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_ResultValue_ok_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultValue_err_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_45 arg2);
extern swig_type_46 _wrap_ResultValue_err_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_ResultValue__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(swig_type_47 arg1, swig_type_48 arg2);
extern uintptr_t _wrap_new_ResultValue__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_49 arg1);
extern uintptr_t _wrap_new_ResultValue__SWIG_2_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_ResultValue__SWIG_3_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_ResultValue__SWIG_4_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_delete_ResultValue_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultBool_result_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_ResultBool_result_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultBool_ok_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_ResultBool_ok_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_ResultBool_err_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_50 arg2);
extern swig_type_51 _wrap_ResultBool_err_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_ResultBool__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(_Bool arg1, swig_type_52 arg2);
extern uintptr_t _wrap_new_ResultBool__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(_Bool arg1);
extern uintptr_t _wrap_new_ResultBool__SWIG_2_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_ResultBool__SWIG_3_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_ResultBool__SWIG_4_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_delete_ResultBool_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_UException__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_UException__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_53 arg1);
extern uintptr_t _wrap_new_UException__SWIG_2_uniset_internal_api_576c1e11c33cb6aa(swig_type_54 arg1);
extern void _wrap_delete_UException_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern swig_type_55 _wrap_UException_getError_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_UException_err_set_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_56 arg2);
extern swig_type_57 _wrap_UException_err_get_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern uintptr_t _wrap_new_UTimeOut__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_UTimeOut__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_58 arg1);
extern void _wrap_delete_UTimeOut_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern swig_type_59 _wrap_UTimeOut_getError_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base);
extern void _wrap_SetUTimeOut_Err_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base, swig_type_60 arg1);
extern swig_type_61 _wrap_GetUTimeOut_Err_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base);
extern uintptr_t _wrap_new_USysError__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_USysError__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_62 arg1);
extern void _wrap_delete_USysError_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern swig_type_63 _wrap_USysError_getError_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base);
extern void _wrap_SetUSysError_Err_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base, swig_type_64 arg1);
extern swig_type_65 _wrap_GetUSysError_Err_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base);
extern uintptr_t _wrap_new_UValidateError__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(void);
extern uintptr_t _wrap_new_UValidateError__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_66 arg1);
extern void _wrap_delete_UValidateError_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern swig_type_67 _wrap_UValidateError_getError_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base);
extern void _wrap_SetUValidateError_Err_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base, swig_type_68 arg1);
extern swig_type_69 _wrap_GetUValidateError_Err_uniset_internal_api_576c1e11c33cb6aa(uintptr_t _swig_base);
extern uintptr_t _wrap_new_UProxy__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(swig_type_70 arg1);
extern uintptr_t _wrap_new_UProxy__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(swig_type_71 arg1);
extern void _wrap_delete_UProxy_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
extern void _wrap_UProxy_askSensor_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_72 arg2);
extern swig_type_73 _wrap_UProxy_getValue_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_74 arg2);
extern void _wrap_UProxy_setValue_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_75 arg2, swig_type_76 arg3);
extern uintptr_t _wrap_UProxy_waitMessage_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_UProxy_safeWaitMessage_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_intgo arg2);
extern uintptr_t _wrap_UProxy_safeSetValue_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_77 arg2, swig_type_78 arg3);
extern uintptr_t _wrap_UProxy_safeGetValue_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_79 arg2);
extern uintptr_t _wrap_UProxy_safeAskSensor_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_80 arg2);
extern _Bool _wrap_UProxy_isExist_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_type_81 arg2);
extern _Bool _wrap_UProxy_run_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_UProxy_terminate_uniset_internal_api_576c1e11c33cb6aa(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

func Uniset_init_params(arg1 Params, arg2 string) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_uniset_init_params_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func Uniset_init(arg1 int, arg2 *string, arg3 string) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_uniset_init_uniset_internal_api_576c1e11c33cb6aa(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_2)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func GetValue(arg1 int64) (_swig_ret ResultValue) {
	var swig_r ResultValue
	_swig_i_0 := arg1
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_getValue_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_3(_swig_i_0))))
	return swig_r
}

func SetValue__SWIG_0(arg1 int64, arg2 int64, arg3 int64) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_setValue__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_4(_swig_i_0), C.swig_type_5(_swig_i_1), C.swig_type_6(_swig_i_2))))
	return swig_r
}

func SetValue__SWIG_1(arg1 int64, arg2 int64) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_setValue__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_7(_swig_i_0), C.swig_type_8(_swig_i_1))))
	return swig_r
}

func SetValue(a ...interface{}) ResultBool {
	argc := len(a)
	if argc == 2 {
		return SetValue__SWIG_1(a[0].(int64), a[1].(int64))
	}
	if argc == 3 {
		return SetValue__SWIG_0(a[0].(int64), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func GetSensorID(arg1 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_getSensorID_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_10)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func GetObjectID(arg1 string) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_getObjectID_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_12)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func GetShortName(arg1 int64) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_getShortName_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_14(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetName(arg1 int64) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_getName_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_16(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetTextName(arg1 int64) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_getTextName_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_18(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetConfFileName() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_getConfFileName_uniset_internal_api_576c1e11c33cb6aa()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetConfigParamsByName__SWIG_0(arg1 string, arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_getConfigParamsByName__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_21)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetConfigParamsByName__SWIG_1(arg1 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_getConfigParamsByName__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_24)(unsafe.Pointer(&_swig_i_0)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func GetConfigParamsByName(a ...interface{}) string {
	argc := len(a)
	if argc == 1 {
		return GetConfigParamsByName__SWIG_1(a[0].(string))
	}
	if argc == 2 {
		return GetConfigParamsByName__SWIG_0(a[0].(string), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func GetDefaultID() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_DefaultID_get_uniset_internal_api_576c1e11c33cb6aa())
	return swig_r
}

func GetDefaultSupplerID() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_DefaultSupplerID_get_uniset_internal_api_576c1e11c33cb6aa())
	return swig_r
}

type SwigcptrParams uintptr

func (p SwigcptrParams) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrParams) SwigIsParams() {
}

func _swig_getParams_Params_max_Params() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_Params_max_Params_uniset_internal_api_576c1e11c33cb6aa())
	return swig_r
}

var ParamsMax int = _swig_getParams_Params_max_Params()
func NewParams() (_swig_ret Params) {
	var swig_r Params
	swig_r = (Params)(SwigcptrParams(C._wrap_new_Params_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func (arg1 SwigcptrParams) Add(arg2 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_Params_add_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParams) Add_str(arg2 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_Params_add_str_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrParams) SetArgc(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Params_argc_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrParams) GetArgc() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Params_argc_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrParams) SetArgv(arg2 *string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Params_argv_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrParams) GetArgv() (_swig_ret *string) {
	var swig_r *string
	_swig_i_0 := arg1
	swig_r = (*string)(C._wrap_Params_argv_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ParamsInst() (_swig_ret Params) {
	var swig_r Params
	swig_r = (Params)(SwigcptrParams(C._wrap_Params_inst_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func DeleteParams(arg1 Params) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Params_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

type Params interface {
	Swigcptr() uintptr
	SwigIsParams()
	Add(arg2 string) (_swig_ret bool)
	Add_str(arg2 string) (_swig_ret bool)
	SetArgc(arg2 int)
	GetArgc() (_swig_ret int)
	SetArgv(arg2 *string)
	GetArgv() (_swig_ret *string)
}

type SwigcptrShortIOInfo uintptr

func (p SwigcptrShortIOInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrShortIOInfo) SwigIsShortIOInfo() {
}

func (arg1 SwigcptrShortIOInfo) SetId(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_id_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_29(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetId() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_id_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShortIOInfo) SetValue(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_value_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_31(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetValue() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_value_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShortIOInfo) SetTv_sec(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_tv_sec_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_33(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetTv_sec() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_tv_sec_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShortIOInfo) SetTv_nsec(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_tv_nsec_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_35(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetTv_nsec() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_tv_nsec_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShortIOInfo) SetSupplier(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_supplier_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_37(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetSupplier() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_supplier_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShortIOInfo) SetConsumer(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_consumer_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_39(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetConsumer() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_consumer_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrShortIOInfo) SetNode(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ShortIOInfo_node_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_41(_swig_i_1))
}

func (arg1 SwigcptrShortIOInfo) GetNode() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ShortIOInfo_node_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewShortIOInfo() (_swig_ret ShortIOInfo) {
	var swig_r ShortIOInfo
	swig_r = (ShortIOInfo)(SwigcptrShortIOInfo(C._wrap_new_ShortIOInfo_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func DeleteShortIOInfo(arg1 ShortIOInfo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ShortIOInfo_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

type ShortIOInfo interface {
	Swigcptr() uintptr
	SwigIsShortIOInfo()
	SetId(arg2 int64)
	GetId() (_swig_ret int64)
	SetValue(arg2 int64)
	GetValue() (_swig_ret int64)
	SetTv_sec(arg2 int64)
	GetTv_sec() (_swig_ret int64)
	SetTv_nsec(arg2 int64)
	GetTv_nsec() (_swig_ret int64)
	SetSupplier(arg2 int64)
	GetSupplier() (_swig_ret int64)
	SetConsumer(arg2 int64)
	GetConsumer() (_swig_ret int64)
	SetNode(arg2 int64)
	GetNode() (_swig_ret int64)
}

type SwigcptrResultIO uintptr

func (p SwigcptrResultIO) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrResultIO) SwigIsResultIO() {
}

func (arg1 SwigcptrResultIO) SetSinfo(arg2 ShortIOInfo) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ResultIO_sinfo_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrResultIO) GetSinfo() (_swig_ret ShortIOInfo) {
	var swig_r ShortIOInfo
	_swig_i_0 := arg1
	swig_r = (ShortIOInfo)(SwigcptrShortIOInfo(C._wrap_ResultIO_sinfo_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrResultIO) SetOk(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultIO_ok_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrResultIO) GetOk() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ResultIO_ok_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewResultIO__SWIG_0(arg1 ShortIOInfo, arg2 bool) (_swig_ret ResultIO) {
	var swig_r ResultIO
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (ResultIO)(SwigcptrResultIO(C._wrap_new_ResultIO__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))))
	return swig_r
}

func NewResultIO__SWIG_1() (_swig_ret ResultIO) {
	var swig_r ResultIO
	swig_r = (ResultIO)(SwigcptrResultIO(C._wrap_new_ResultIO__SWIG_1_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewResultIO(a ...interface{}) ResultIO {
	argc := len(a)
	if argc == 0 {
		return NewResultIO__SWIG_1()
	}
	if argc == 2 {
		return NewResultIO__SWIG_0(a[0].(ShortIOInfo), a[1].(bool))
	}
	panic("No match for overloaded function call")
}

func DeleteResultIO(arg1 ResultIO) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ResultIO_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

type ResultIO interface {
	Swigcptr() uintptr
	SwigIsResultIO()
	SetSinfo(arg2 ShortIOInfo)
	GetSinfo() (_swig_ret ShortIOInfo)
	SetOk(arg2 bool)
	GetOk() (_swig_ret bool)
}

type SwigcptrResultValue uintptr

func (p SwigcptrResultValue) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrResultValue) SwigIsResultValue() {
}

func (arg1 SwigcptrResultValue) SetValue(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultValue_value_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_43(_swig_i_1))
}

func (arg1 SwigcptrResultValue) GetValue() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ResultValue_value_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrResultValue) SetOk(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultValue_ok_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrResultValue) GetOk() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ResultValue_ok_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrResultValue) SetErr(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultValue_err_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), *(*C.swig_type_45)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrResultValue) GetErr() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ResultValue_err_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func NewResultValue__SWIG_0(arg1 int64, arg2 string) (_swig_ret ResultValue) {
	var swig_r ResultValue
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_new_ResultValue__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_47(_swig_i_0), *(*C.swig_type_48)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func NewResultValue__SWIG_1(arg1 int64) (_swig_ret ResultValue) {
	var swig_r ResultValue
	_swig_i_0 := arg1
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_new_ResultValue__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_49(_swig_i_0))))
	return swig_r
}

func NewResultValue__SWIG_2() (_swig_ret ResultValue) {
	var swig_r ResultValue
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_new_ResultValue__SWIG_2_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewResultValue__SWIG_3(arg1 uintptr) (_swig_ret ResultValue) {
	var swig_r ResultValue
	_swig_i_0 := arg1
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_new_ResultValue__SWIG_3_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewResultValue__SWIG_4(arg1 ResultValue) (_swig_ret ResultValue) {
	var swig_r ResultValue
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_new_ResultValue__SWIG_4_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewResultValue(a ...interface{}) ResultValue {
	argc := len(a)
	if argc == 0 {
		return NewResultValue__SWIG_2()
	}
	if argc == 1 {
		if _, ok := a[0].(uintptr); !ok {
			goto check_2
		}
		return NewResultValue__SWIG_3(a[0].(uintptr))
	}
check_2:
	if argc == 1 {
		if _, ok := a[0].(SwigcptrResultValue); !ok {
			goto check_3
		}
		return NewResultValue__SWIG_4(a[0].(ResultValue))
	}
check_3:
	if argc == 1 {
		return NewResultValue__SWIG_1(a[0].(int64))
	}
	if argc == 2 {
		return NewResultValue__SWIG_0(a[0].(int64), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func DeleteResultValue(arg1 ResultValue) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ResultValue_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

type ResultValue interface {
	Swigcptr() uintptr
	SwigIsResultValue()
	SetValue(arg2 int64)
	GetValue() (_swig_ret int64)
	SetOk(arg2 bool)
	GetOk() (_swig_ret bool)
	SetErr(arg2 string)
	GetErr() (_swig_ret string)
}

type SwigcptrResultBool uintptr

func (p SwigcptrResultBool) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrResultBool) SwigIsResultBool() {
}

func (arg1 SwigcptrResultBool) SetResult(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultBool_result_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrResultBool) GetResult() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ResultBool_result_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrResultBool) SetOk(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultBool_ok_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrResultBool) GetOk() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ResultBool_ok_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrResultBool) SetErr(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ResultBool_err_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), *(*C.swig_type_50)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrResultBool) GetErr() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_ResultBool_err_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func NewResultBool__SWIG_0(arg1 bool, arg2 string) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_new_ResultBool__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(C._Bool(_swig_i_0), *(*C.swig_type_52)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func NewResultBool__SWIG_1(arg1 bool) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_new_ResultBool__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(C._Bool(_swig_i_0))))
	return swig_r
}

func NewResultBool__SWIG_2() (_swig_ret ResultBool) {
	var swig_r ResultBool
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_new_ResultBool__SWIG_2_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewResultBool__SWIG_3(arg1 uintptr) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_new_ResultBool__SWIG_3_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewResultBool__SWIG_4(arg1 ResultBool) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_new_ResultBool__SWIG_4_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewResultBool(a ...interface{}) ResultBool {
	argc := len(a)
	if argc == 0 {
		return NewResultBool__SWIG_2()
	}
	if argc == 1 {
		if _, ok := a[0].(uintptr); !ok {
			goto check_2
		}
		return NewResultBool__SWIG_3(a[0].(uintptr))
	}
check_2:
	if argc == 1 {
		if _, ok := a[0].(SwigcptrResultBool); !ok {
			goto check_3
		}
		return NewResultBool__SWIG_4(a[0].(ResultBool))
	}
check_3:
	if argc == 1 {
		return NewResultBool__SWIG_1(a[0].(bool))
	}
	if argc == 2 {
		return NewResultBool__SWIG_0(a[0].(bool), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func DeleteResultBool(arg1 ResultBool) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ResultBool_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

type ResultBool interface {
	Swigcptr() uintptr
	SwigIsResultBool()
	SetResult(arg2 bool)
	GetResult() (_swig_ret bool)
	SetOk(arg2 bool)
	GetOk() (_swig_ret bool)
	SetErr(arg2 string)
	GetErr() (_swig_ret string)
}

type SwigcptrUException uintptr

func (p SwigcptrUException) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUException) SwigIsUException() {
}

func NewUException__SWIG_0() (_swig_ret UException) {
	var swig_r UException
	swig_r = (UException)(SwigcptrUException(C._wrap_new_UException__SWIG_0_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewUException__SWIG_1(arg1 string) (_swig_ret UException) {
	var swig_r UException
	_swig_i_0 := arg1
	swig_r = (UException)(SwigcptrUException(C._wrap_new_UException__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_53)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func NewUException__SWIG_2(arg1 string) (_swig_ret UException) {
	var swig_r UException
	_swig_i_0 := arg1
	swig_r = (UException)(SwigcptrUException(C._wrap_new_UException__SWIG_2_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_54)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func NewUException(a ...interface{}) UException {
	argc := len(a)
	if argc == 0 {
		return NewUException__SWIG_0()
	}
	if argc == 1 {
		return NewUException__SWIG_1(a[0].(string))
	}
	if argc == 1 {
		return NewUException__SWIG_2(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func DeleteUException(arg1 UException) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_UException_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrUException) GetError() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_UException_getError_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrUException) SetErr(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_UException_err_set_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), *(*C.swig_type_56)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrUException) GetErr() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_UException_err_get_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

type UException interface {
	Swigcptr() uintptr
	SwigIsUException()
	GetError() (_swig_ret string)
	SetErr(arg2 string)
	GetErr() (_swig_ret string)
}

type SwigcptrUTimeOut uintptr

func (p SwigcptrUTimeOut) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUTimeOut) SwigIsUTimeOut() {
}

func NewUTimeOut__SWIG_0() (_swig_ret UTimeOut) {
	var swig_r UTimeOut
	swig_r = (UTimeOut)(SwigcptrUTimeOut(C._wrap_new_UTimeOut__SWIG_0_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewUTimeOut__SWIG_1(arg1 string) (_swig_ret UTimeOut) {
	var swig_r UTimeOut
	_swig_i_0 := arg1
	swig_r = (UTimeOut)(SwigcptrUTimeOut(C._wrap_new_UTimeOut__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_58)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func NewUTimeOut(a ...interface{}) UTimeOut {
	argc := len(a)
	if argc == 0 {
		return NewUTimeOut__SWIG_0()
	}
	if argc == 1 {
		return NewUTimeOut__SWIG_1(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func DeleteUTimeOut(arg1 UTimeOut) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_UTimeOut_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrUTimeOut) GetError() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_UTimeOut_getError_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (_swig_base SwigcptrUTimeOut) SetErr(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_SetUTimeOut_Err_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base), *(*C.swig_type_60)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func (_swig_base SwigcptrUTimeOut) GetErr() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_GetUTimeOut_Err_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (p SwigcptrUTimeOut) SwigIsUException() {
}

func (p SwigcptrUTimeOut) SwigGetUException() UException {
	return SwigcptrUException(p.Swigcptr())
}

type UTimeOut interface {
	Swigcptr() uintptr
	SwigIsUTimeOut()
	GetError() (_swig_ret string)
	SetErr(arg1 string)
	GetErr() (_swig_ret string)
	SwigIsUException()
	SwigGetUException() UException
}

type SwigcptrUSysError uintptr

func (p SwigcptrUSysError) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUSysError) SwigIsUSysError() {
}

func NewUSysError__SWIG_0() (_swig_ret USysError) {
	var swig_r USysError
	swig_r = (USysError)(SwigcptrUSysError(C._wrap_new_USysError__SWIG_0_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewUSysError__SWIG_1(arg1 string) (_swig_ret USysError) {
	var swig_r USysError
	_swig_i_0 := arg1
	swig_r = (USysError)(SwigcptrUSysError(C._wrap_new_USysError__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_62)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func NewUSysError(a ...interface{}) USysError {
	argc := len(a)
	if argc == 0 {
		return NewUSysError__SWIG_0()
	}
	if argc == 1 {
		return NewUSysError__SWIG_1(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func DeleteUSysError(arg1 USysError) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_USysError_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrUSysError) GetError() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_USysError_getError_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (_swig_base SwigcptrUSysError) SetErr(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_SetUSysError_Err_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base), *(*C.swig_type_64)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func (_swig_base SwigcptrUSysError) GetErr() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_GetUSysError_Err_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (p SwigcptrUSysError) SwigIsUException() {
}

func (p SwigcptrUSysError) SwigGetUException() UException {
	return SwigcptrUException(p.Swigcptr())
}

type USysError interface {
	Swigcptr() uintptr
	SwigIsUSysError()
	GetError() (_swig_ret string)
	SetErr(arg1 string)
	GetErr() (_swig_ret string)
	SwigIsUException()
	SwigGetUException() UException
}

type SwigcptrUValidateError uintptr

func (p SwigcptrUValidateError) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUValidateError) SwigIsUValidateError() {
}

func NewUValidateError__SWIG_0() (_swig_ret UValidateError) {
	var swig_r UValidateError
	swig_r = (UValidateError)(SwigcptrUValidateError(C._wrap_new_UValidateError__SWIG_0_uniset_internal_api_576c1e11c33cb6aa()))
	return swig_r
}

func NewUValidateError__SWIG_1(arg1 string) (_swig_ret UValidateError) {
	var swig_r UValidateError
	_swig_i_0 := arg1
	swig_r = (UValidateError)(SwigcptrUValidateError(C._wrap_new_UValidateError__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_66)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func NewUValidateError(a ...interface{}) UValidateError {
	argc := len(a)
	if argc == 0 {
		return NewUValidateError__SWIG_0()
	}
	if argc == 1 {
		return NewUValidateError__SWIG_1(a[0].(string))
	}
	panic("No match for overloaded function call")
}

func DeleteUValidateError(arg1 UValidateError) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_UValidateError_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrUValidateError) GetError() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_UValidateError_getError_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (_swig_base SwigcptrUValidateError) SetErr(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_SetUValidateError_Err_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base), *(*C.swig_type_68)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func (_swig_base SwigcptrUValidateError) GetErr() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_GetUValidateError_Err_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_base))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (p SwigcptrUValidateError) SwigIsUException() {
}

func (p SwigcptrUValidateError) SwigGetUException() UException {
	return SwigcptrUException(p.Swigcptr())
}

type UValidateError interface {
	Swigcptr() uintptr
	SwigIsUValidateError()
	GetError() (_swig_ret string)
	SetErr(arg1 string)
	GetErr() (_swig_ret string)
	SwigIsUException()
	SwigGetUException() UException
}

type SwigcptrUProxy uintptr

func (p SwigcptrUProxy) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUProxy) SwigIsUProxy() {
}

func NewUProxy__SWIG_0(arg1 string) (_swig_ret UProxy) {
	var swig_r UProxy
	_swig_i_0 := arg1
	swig_r = (UProxy)(SwigcptrUProxy(C._wrap_new_UProxy__SWIG_0_uniset_internal_api_576c1e11c33cb6aa(*(*C.swig_type_70)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func NewUProxy__SWIG_1(arg1 int64) (_swig_ret UProxy) {
	var swig_r UProxy
	_swig_i_0 := arg1
	swig_r = (UProxy)(SwigcptrUProxy(C._wrap_new_UProxy__SWIG_1_uniset_internal_api_576c1e11c33cb6aa(C.swig_type_71(_swig_i_0))))
	return swig_r
}

func NewUProxy(a ...interface{}) UProxy {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(string); !ok {
			goto check_1
		}
		return NewUProxy__SWIG_0(a[0].(string))
	}
check_1:
	if argc == 1 {
		return NewUProxy__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func DeleteUProxy(arg1 UProxy) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_UProxy_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrUProxy) AskSensor(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_UProxy_askSensor_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_72(_swig_i_1))
}

func (arg1 SwigcptrUProxy) GetValue(arg2 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_UProxy_getValue_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_74(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrUProxy) SetValue(arg2 int64, arg3 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_UProxy_setValue_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_75(_swig_i_1), C.swig_type_76(_swig_i_2))
}

func (arg1 SwigcptrUProxy) WaitMessage(arg2 int) (_swig_ret ShortIOInfo) {
	var swig_r ShortIOInfo
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ShortIOInfo)(SwigcptrShortIOInfo(C._wrap_UProxy_waitMessage_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrUProxy) SafeWaitMessage(arg2 int) (_swig_ret ResultIO) {
	var swig_r ResultIO
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ResultIO)(SwigcptrResultIO(C._wrap_UProxy_safeWaitMessage_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrUProxy) SafeSetValue(arg2 int64, arg3 int64) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_UProxy_safeSetValue_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_77(_swig_i_1), C.swig_type_78(_swig_i_2))))
	return swig_r
}

func (arg1 SwigcptrUProxy) SafeGetValue(arg2 int64) (_swig_ret ResultValue) {
	var swig_r ResultValue
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ResultValue)(SwigcptrResultValue(C._wrap_UProxy_safeGetValue_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_79(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrUProxy) SafeAskSensor(arg2 int64) (_swig_ret ResultBool) {
	var swig_r ResultBool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (ResultBool)(SwigcptrResultBool(C._wrap_UProxy_safeAskSensor_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_80(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrUProxy) IsExist(arg2 int64) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_UProxy_isExist_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_type_81(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrUProxy) Run(arg2 int) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_UProxy_run_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrUProxy) Terminate() {
	_swig_i_0 := arg1
	C._wrap_UProxy_terminate_uniset_internal_api_576c1e11c33cb6aa(C.uintptr_t(_swig_i_0))
}

type UProxy interface {
	Swigcptr() uintptr
	SwigIsUProxy()
	AskSensor(arg2 int64)
	GetValue(arg2 int64) (_swig_ret int64)
	SetValue(arg2 int64, arg3 int64)
	WaitMessage(arg2 int) (_swig_ret ShortIOInfo)
	SafeWaitMessage(arg2 int) (_swig_ret ResultIO)
	SafeSetValue(arg2 int64, arg3 int64) (_swig_ret ResultBool)
	SafeGetValue(arg2 int64) (_swig_ret ResultValue)
	SafeAskSensor(arg2 int64) (_swig_ret ResultBool)
	IsExist(arg2 int64) (_swig_ret bool)
	Run(arg2 int) (_swig_ret bool)
	Terminate()
}
