version: '2'

services:
  ch:
    image: 'clickhouse/clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - './testsuite/config.xml:/etc/clickhouse-server/config.xml'
      - './testsuite/clickhouse_uniset_dictionary.xml:/etc/clickhouse-server/clickhouse_uniset_dictionary.xml'
      - './testsuite/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './testsuite/data:/usr/share/uniset/data'
