# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyUConnector', [dirname(__file__)])
        except ImportError:
            import _pyUConnector
            return _pyUConnector
        if fp is not None:
            try:
                _mod = imp.load_module('_pyUConnector', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyUConnector = swig_import_helper()
    del swig_import_helper
else:
    import _pyUConnector
del version_info

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class Params:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Params, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Params, name)
    __repr__ = _swig_repr
    max = _pyUConnector.Params_max

    def __init__(self):
        this = _pyUConnector.new_Params()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def add(self, s):
        return _pyUConnector.Params_add(self, s)

    def add_str(self, s):
        return _pyUConnector.Params_add_str(self, s)
    __swig_setmethods__["argc"] = _pyUConnector.Params_argc_set
    __swig_getmethods__["argc"] = _pyUConnector.Params_argc_get
    __swig_setmethods__["argv"] = _pyUConnector.Params_argv_set
    __swig_getmethods__["argv"] = _pyUConnector.Params_argv_get
    __swig_getmethods__["inst"] = lambda x: _pyUConnector.Params_inst
    __swig_destroy__ = _pyUConnector.delete_Params
    __del__ = lambda self: None
Params_swigregister = _pyUConnector.Params_swigregister
Params_swigregister(Params)
cvar = _pyUConnector.cvar
DefaultID = cvar.DefaultID
DefaultSupplerID = cvar.DefaultSupplerID

def Params_inst():
    return _pyUConnector.Params_inst()
Params_inst = _pyUConnector.Params_inst

class ShortIOInfo:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ShortIOInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ShortIOInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["value"] = _pyUConnector.ShortIOInfo_value_set
    __swig_getmethods__["value"] = _pyUConnector.ShortIOInfo_value_get
    __swig_setmethods__["tv_sec"] = _pyUConnector.ShortIOInfo_tv_sec_set
    __swig_getmethods__["tv_sec"] = _pyUConnector.ShortIOInfo_tv_sec_get
    __swig_setmethods__["tv_nsec"] = _pyUConnector.ShortIOInfo_tv_nsec_set
    __swig_getmethods__["tv_nsec"] = _pyUConnector.ShortIOInfo_tv_nsec_get
    __swig_setmethods__["supplier"] = _pyUConnector.ShortIOInfo_supplier_set
    __swig_getmethods__["supplier"] = _pyUConnector.ShortIOInfo_supplier_get
    __swig_setmethods__["supplier_node"] = _pyUConnector.ShortIOInfo_supplier_node_set
    __swig_getmethods__["supplier_node"] = _pyUConnector.ShortIOInfo_supplier_node_get

    def __init__(self):
        this = _pyUConnector.new_ShortIOInfo()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _pyUConnector.delete_ShortIOInfo
    __del__ = lambda self: None
ShortIOInfo_swigregister = _pyUConnector.ShortIOInfo_swigregister
ShortIOInfo_swigregister(ShortIOInfo)

class UConnector:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UConnector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UConnector, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pyUConnector.new_UConnector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _pyUConnector.delete_UConnector
    __del__ = lambda self: None

    def getUIType(self):
        return _pyUConnector.UConnector_getUIType(self)

    def getConfFileName(self):
        return _pyUConnector.UConnector_getConfFileName(self)

    def getValue(self, id, node):
        return _pyUConnector.UConnector_getValue(self, id, node)

    def setValue(self, *args):
        return _pyUConnector.UConnector_setValue(self, *args)

    def getTimeChange(self, *args):
        return _pyUConnector.UConnector_getTimeChange(self, *args)

    def getSensorID(self, name):
        return _pyUConnector.UConnector_getSensorID(self, name)

    def getNodeID(self, name):
        return _pyUConnector.UConnector_getNodeID(self, name)

    def getObjectID(self, name):
        return _pyUConnector.UConnector_getObjectID(self, name)

    def getShortName(self, id):
        return _pyUConnector.UConnector_getShortName(self, id)

    def getName(self, id):
        return _pyUConnector.UConnector_getName(self, id)

    def getTextName(self, id):
        return _pyUConnector.UConnector_getTextName(self, id)

    def getObjectInfo(self, *args):
        return _pyUConnector.UConnector_getObjectInfo(self, *args)

    def apiRequest(self, *args):
        return _pyUConnector.UConnector_apiRequest(self, *args)

    def activate_objects(self):
        return _pyUConnector.UConnector_activate_objects(self)
UConnector_swigregister = _pyUConnector.UConnector_swigregister
UConnector_swigregister(UConnector)

# This file is compatible with both classic and new-style classes.
