#!/bin/sh


usage()
{
	echo "Usage: ${0##*/} dbfile"
}

[ -z "$1" ] && usage && exit 1
dbfile="$1"

[ -a "$dbfile" ] && echo "$dbfile already exists.." && exit 1


sqlite3 $dbfile <<"_EOF_"

PRAGMA foreign_keys=ON;

DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tms timestamp KEY default (strftime('%s', 'now')),
  usec INTEGER(5) NOT NULL,
  name TEXT KEY NOT NULL,
  text TEXT
);

_EOF_
