/* This file is part of the UniSet project
 * Copyright (c) 2002 Free Software Foundation, Inc.
 * Copyright (c) 2002 Pavel Vainerman
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
// --------------------------------------------------------------------------
/*! \file
 *  \author Pavel Vainerman
*/
// --------------------------------------------------------------------------
#ifndef UniSetObject_i_IDL_
#define UniSetObject_i_IDL_
// ---------------------------------------------------------------------------
#include "UniSetTypes_i.idl"

// ---------------------------------------------------------------------------
//module UniSet
//{
    /*!
     * \interface UniSetObject_i
     * \brief Базовый интерфес для всех объектов
     * \author Pavel Vainerman
     *
     * Первичный базовый класс. Прародитель всех объектов в системе.
     *
    */
    interface UniSetObject_i
    {
        UniSetTypes::ObjectId getId();       /*!< получение идентификатора объекта */
        UniSetTypes::ObjectType getType();   /*!< получение типа объекта */

        /*! получение информации о внутреннем состоянии объекта
            \param userparam - Необязательный пользовательский параметр
        */
        UniSetTypes::SimpleInfo getInfo( in long userparam );

        boolean exist();   /*!< проверка существования объекта */

        /*!  Функция посылки сообщения объекту */
        void push(in UniSetTypes::TransportMessage msg);
    };

//};    // end of module UniSet

#endif
// --------------------------------------------------------------------------------------------------------------
