/*
 * Copyright (c) 2015 Pavel Vainerman.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, version 2.1.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
// --------------------------------------------------------------------------
/*! \file
 *  \author Pavel Vainerman
*/
// --------------------------------------------------------------------------
#ifndef UniSetObject_i_IDL_
#define UniSetObject_i_IDL_
// ---------------------------------------------------------------------------
#include "UniSetTypes_i.idl"

// ---------------------------------------------------------------------------
//module UniSet
//{
    /*!
     * \interface UniSetObject_i
     * \brief Базовый интерфес для всех объектов
     * \author Pavel Vainerman
     *
     * Первичный базовый класс. Прародитель всех объектов в системе.
     *
    */
    interface UniSetObject_i
    {
        uniset::ObjectId getId();       /*!< получение идентификатора объекта */
        uniset::ObjectType getType();   /*!< получение типа объекта */

        /*! получение информации о внутреннем состоянии объекта
            \param userparam - Необязательный пользовательский параметр
        */
        uniset::SimpleInfo getInfo( in long userparam );

        boolean exist();   /*!< проверка существования объекта */

        /*!  Функция посылки сообщения объекту */
        void push(in uniset::TransportMessage msg);
    };

//};    // end of module UniSet

#endif
// --------------------------------------------------------------------------------------------------------------
