/* This file is part of the UniSet project
 * Copyright (c) 2002 Free Software Foundation, Inc.
 * Copyright (c) 2002 Pavel Vainerman
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
// --------------------------------------------------------------------------
/*! \file
 *  \author Pavel Vainerman
*/
// --------------------------------------------------------------------------
#ifndef UniSetManager_i_IDL_
#define UniSetManager_i_IDL_
// ---------------------------------------------------------------------------
#include "UniSetObject_i.idl"
#include "UniSetTypes_i.idl"
// ---------------------------------------------------------------------------
//module UniSet
//{

    /*!
     * \interface UniSetManager_i
     * \brief Интерфейс менеджера объектов
     * \author Pavel Vainerman
     * \version 
     * \date   September 2001-
     *
     * Базовый класс для менеджеров объектов. Позволяет посылать сообщение
     * ко всем объектам сразу.
    */
    interface UniSetManager_i : UniSetObject_i
    {
        /*!< распространить сообщение всем подчиненным объектам */
        void broadcast(in UniSetTypes::TransportMessage msg);    
        
        /*! получение информации о состоянии подчиненных объектов(менеджеров)
         * \param MaxLength  - ограничение размера возвращаемой
         * последовательности структур SimpleInfo. 
         * \note Если у менеджера количество подчиненных объектов 
         * больше MaxLength, то он вернет информацию только 
         * о первых MaxLength объектах. Если <=, то количество
         * равное количеству объектов.
         * \note Возвращаемые данные содержат в себе инфо. о всех 
         * подчиненных объектах данного менеджера, а также объектах
         * подчиненных данному менеджеру менеджерах и их объектах
         * и т.п. и т.п. рекурсивно... Так что MaxLength должно быть 
         * достаточным.
         * \todo Подумать насчет применения итератора, при слишком 
         * большом( >1000 ) количестве подчиненных объектов...
         */
        UniSetTypes::SimpleInfoSeq getObjectsInfo( in long MaxLength );
    };

//};    // end of module UniSet
#endif
// --------------------------------------------------------------------------------------------------------------
