/* This file is part of the UniSet project
 * Copyright (c) 2002 Free Software Foundation, Inc.
 * Copyright (c) 2002 Pavel Vainerman
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
// --------------------------------------------------------------------------
/*! \file
 *  \author Pavel Vainerman
*/
// --------------------------------------------------------------------------
#ifndef BaseIOController_i_IDL_
#define BaseIOController_i_IDL_
// --------------------------------------------------------------------------
#include "../UniSetTypes/UniSetTypes_i.idl"
#include "../UniSetTypes/UniSetManager_i.idl"
// --------------------------------------------------------------------------------------------------------------

/*! 
 * \interface IOController_i 
 * \brief Базовый интерфейс для создания координаторов ввода/вывода  
 *
*/ 
interface IOController_i : UniSetManager_i
{
    // исключения

    /*! Датчик не найден */
    exception NameNotFound
    {
        string err;
    };

    exception IOBadParam
    {
        string err;
    };

    /*! Значение не определено
        (например: обрыв датчика)
    */
    exception Undefined
    {
    };

    /*! Информация о датчике */
    struct SensorInfo
    {
        UniSetTypes::ObjectId id;    /*!< идентификатор датчика */
        UniSetTypes::ObjectId node;  /*!< узел на котором он находится */
    };

    long getValue(in UniSetTypes::ObjectId sid) raises(NameNotFound,Undefined);
    void setValue(in UniSetTypes::ObjectId sid, in long value,
                    in UniSetTypes::ObjectId sup_id) raises(NameNotFound);

    // установка неопределённого состояния
    // (пока работает только для аналоговых датчиков)
    void setUndefinedState(in UniSetTypes::ObjectId sid, in boolean undefined, in UniSetTypes::ObjectId sup_id )
                            raises(NameNotFound);

    // fast version (не вырабатывает исключения)
    oneway void fastSetValue(in UniSetTypes::ObjectId sid, in long value, in UniSetTypes::ObjectId sup_id);

    UniversalIO::IOType getIOType(in UniSetTypes::ObjectId sid) raises(NameNotFound);

    // --- Интерфейс для конфигурирования ---

    /*! Получение неколиброванного значения */
    long getRawValue( in UniSetTypes::ObjectId sid ) raises(NameNotFound);

    struct CalibrateInfo
    {
        long minRaw;      /*!< минимальное "сырое" значение */
        long maxRaw;      /*!< максимальное "сырое" значение */
        long minCal;      /*!< минимальное калиброванное значение */
        long maxCal;      /*!< максимальное калиброванное значение */
        short precision;  /*!< точность */
    };

    void calibrate( in UniSetTypes::ObjectId sid, in CalibrateInfo ci, in UniSetTypes::ObjectId adminId ) raises(NameNotFound);
    CalibrateInfo getCalibrateInfo( in UniSetTypes::ObjectId sid ) raises(NameNotFound);

    // --- Интерфес получения информации о всех датчиках ---
    /*! Информация об аналоговом датчике */
    struct SensorIOInfo
    {
        long value;                   /*!< значение */
        boolean undefined;            /*!< признак неопределённости значения */
        boolean blocked;              /*!< данное значение блокировано другим */
        long real_value;              /*!< запомненное состояние, до блокировки */
        UniversalIO::IOType type;     /*!< тип */
        long priority;                /*!< приоритет уведомления */
        IOController_i::SensorInfo si;
        long default_val;             /*!< значение по умолчанию */
        CalibrateInfo ci;             /*!< калибровочные параметры */
        long tv_sec;                  /*!< время последнего изменения датчика, секунды (gettimeofday) */
        long tv_usec;                 /*!< время последнего изменения датчика, мксек (gettimeofday) */
        boolean dbignore;             /*!< не сохранять изменения в БД */
    };

    typedef sequence<SensorIOInfo> SensorInfoSeq;

    SensorInfoSeq getSensorsMap();
    SensorIOInfo getSensorIOInfo( in UniSetTypes::ObjectId sid ) raises(NameNotFound);

    // -- Функции работы со списком датчиков --

    /*! Получение состояния датчиков. */
    SensorInfoSeq getSensorSeq( in UniSetTypes::IDSeq lst );

    /*! Информация о "выходе" */
    struct OutInfo
    {
        SensorInfo si;    /*!< идентификатор выхода */
        long value;       /*!< значение */
    };

    typedef sequence<OutInfo> OutSeq;

    /*!
        Выставить состояние группы датчиков/выходов (дискретных или аналоговых).
        \return Возвращает список входов/выходов изменить состояние которых не удалось.
            Будет пустым если всё хорошо.
    */
    UniSetTypes::IDSeq setOutputSeq( in OutSeq lst, in UniSetTypes::ObjectId sup_id );


    /*! Информация о дискретном датчике */
    struct ShortIOInfo
    {
        long value;
        long tv_sec;    /*!< время последнего изменения датчика, секунды (gettimeofday) */
        long tv_usec;   /*!< время последнего изменения датчика, мксек (gettimeofday) */
    };

    ShortIOInfo getChangedTime( in UniSetTypes::ObjectId sid ) raises(NameNotFound);


    /*! Информация о дискретном датчике */
    struct ShortMap
    {
        UniversalIO::IOType type;
        long value;
        long id;
    };

    typedef sequence<ShortMap> ShortMapSeq;

    ShortMapSeq getSensors();
};

// --------------------------------------------------------------------------------------------------------------
/*!
 * \interface IONotifyController_i
 * \brief Базовый интерфейс для создания процессов рассылающих сообщения об изменении состояния
 * \author Pavel Vainerman
 * \version
 * \date   September 2001-
 *
 * ... а здесь идет кратенькое описание...
*/
interface IONotifyController_i : IOController_i
{
    /*! Неверно указаны пределы */
    exception BadRange
    {
    };

    /*! Универсальная функция заказа уведомления об изменнии датчика.
     *    Позволяет заказывать как дискретные так и аналоговые датчики
     * \sa UniversalIO::UniversalIOController::askSensor()
    */
    void askSensor(in UniSetTypes::ObjectId sid, in UniSetTypes::ConsumerInfo ci, in UniversalIO::UIOCommand cmd ) raises(NameNotFound,IOBadParam);

    /*!
        Заказ сразу списка объектов.
        \return Возвращает список объектов заказ по котором не прошёл.
            Будет пустым если всё хорошо.
    */
    UniSetTypes::IDSeq askSensorsSeq( in UniSetTypes::IDSeq lst,
                                        in UniSetTypes::ConsumerInfo ci,
                                        in UniversalIO::UIOCommand cmd );


    /*! Состояние порогового датчика */
    enum ThresholdState
    {
        LowThreshold,       /*!< сработал нижний порог  (значение меньше нижнего) */
        NormalThreshold,    /*!< значение в заданных пределах (не достигли порога) */
        HiThreshold         /*!< сработал верхний порог  (значение больше верхнего) */
    };

    struct ThresholdInfo
    {
        UniSetTypes::ThresholdId id;
        long hilimit;         /*!< верхняя граница срабатывания */
        long lowlimit;        /*!< нижняя гранийа срабатывания */
        ThresholdState state;
        long tv_sec;          /*!< время последнего изменения датчика, секунды (gettimeofday) */
        long tv_usec;         /*!< время последнего изменения датчика, мксек (gettimeofday) */
        boolean invert;       /*!< инвертированная логика */
    };

    typedef sequence<ThresholdInfo> ThresholdInfoSeq;

    /*! Заказ порогового датчика
     * \sa UniversalIO::UniversalIOController::askThreshold()
     * \param tid - идентификатор порога
     * \param lowLimit - нижний порог срабатыания
     * \param hiLimit - верхний порог срабатывания
     * \param invert - инвертировать логику срабатывания
     * Если invert=false, порог срабатывает при условии >= hilimit и отпускается при <= lowlimit
     * Если invert=true, порог срабатывает при условии <= lowlimit и отпускается при <= hilimit
    */
    void askThreshold(in UniSetTypes::ObjectId sid, in UniSetTypes::ConsumerInfo ci, in UniSetTypes::ThresholdId tid,
                        in long lowLimit, in long hiLimit, in boolean invert,
                        in UniversalIO::UIOCommand cmd ) raises(NameNotFound, IOBadParam, BadRange);


    /*! Получение информации о пороге
     *  Т.к. пороги могут иметь одинаковый tid для разных аналоговых датчиков, то передаётся и SensorInfo
    */
    ThresholdInfo getThresholdInfo( in UniSetTypes::ObjectId sid, in UniSetTypes::ThresholdId tid ) raises(NameNotFound);

    struct ThresholdList
    {
        IOController_i::SensorInfo si;
        UniversalIO::IOType type;
        long value;
        ThresholdInfoSeq tlist;
    };

    typedef sequence<ThresholdList> ThresholdsListSeq;

    /*! получить список порогов для датчка "si" */
    ThresholdList getThresholds( in UniSetTypes::ObjectId sid ) raises(NameNotFound);

    /*! получить список ВСЕХ датчиков по которым созданы пороги */
    ThresholdsListSeq getThresholdsList();
};
// --------------------------------------------------------------------------
#endif
