"""Tests for the st2js code generator (codegen.py).

Tests cover:
- Minimal program generates correct JS structure
- Input variable access generates in_SensorName
- Output variable assignment generates out_SensorName = ...
- Local variable declaration with initial value
- Binary operator mapping (especially = -> ===, AND -> &&)
- If/else emission
- Type coercion (REAL->INT generates Math.round)
- Complete output for minimal.st + minimal_mapping.yaml
"""
from __future__ import annotations

import pytest

from st2js.ir import (
    IECType,
    IRAssignment,
    IRBinaryOp,
    IRCase,
    IRForLoop,
    IRIfElse,
    IRLiteral,
    IRProgram,
    IRRepeatLoop,
    IRTypeCoercion,
    IRUnaryOp,
    IRVarRef,
    IRVariable,
    IRWhileLoop,
)
from st2js.mapping import SensorEntry, SensorMapping, MappingOptions


def _make_program(
    name: str = "Main",
    inputs: list | None = None,
    outputs: list | None = None,
    locals_: list | None = None,
    body: list | None = None,
) -> IRProgram:
    """Helper to create an IRProgram with defaults."""
    return IRProgram(
        name=name,
        inputs=inputs or [],
        outputs=outputs or [],
        locals=locals_ or [],
        fb_instances=[],
        body=body or [],
        function_blocks=[],
    )


def _make_mapping(
    inputs: list[SensorEntry] | None = None,
    outputs: list[SensorEntry] | None = None,
) -> SensorMapping:
    """Helper to create a SensorMapping with defaults."""
    return SensorMapping(
        inputs=inputs or [],
        outputs=outputs or [],
        options=MappingOptions(),
    )


class TestMinimalProgramStructure:
    """Test that a minimal program generates correct JS structure."""

    def test_empty_program_has_load_statement(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert 'load("uniset2-iec61131.js");' in js

    def test_empty_program_has_comment_header(self):
        from st2js.codegen import generate

        program = _make_program(name="Main")
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "// Generated by st2js from Main" in js

    def test_empty_program_has_on_step_function(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "function uniset_on_step()" in js

    def test_empty_program_has_empty_sensor_arrays(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "uniset_inputs = [];" in js
        assert "uniset_outputs = [];" in js

    def test_structure_order(self):
        """Verify load, inputs, outputs, on_step appear in correct order."""
        from st2js.codegen import generate

        program = _make_program()
        mapping = _make_mapping()
        js = generate(program, mapping)

        load_pos = js.index('load("uniset2-iec61131.js")')
        inputs_pos = js.index("uniset_inputs")
        outputs_pos = js.index("uniset_outputs")
        on_step_pos = js.index("function uniset_on_step()")

        assert load_pos < inputs_pos < outputs_pos < on_step_pos


class TestInputVariableAccess:
    """Test input variable access generates in_SensorName."""

    def test_input_var_ref_uses_in_prefix(self):
        from st2js.codegen import generate

        program = _make_program(
            inputs=[
                IRVariable(name="Temperature", iec_type=IECType.REAL, is_input=True),
            ],
            outputs=[
                IRVariable(name="Heater", iec_type=IECType.BOOL, is_output=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="Heater"),
                    value=IRVarRef(name="Temperature"),
                ),
            ],
        )
        mapping = _make_mapping(
            inputs=[SensorEntry(st_name="Temperature", sensor_name="AI_Temp_S")],
            outputs=[SensorEntry(st_name="Heater", sensor_name="DO_Heater_C")],
        )
        js = generate(program, mapping)

        assert "in_AI_Temp_S" in js

    def test_input_sensor_in_uniset_inputs_array(self):
        from st2js.codegen import generate

        program = _make_program(
            inputs=[
                IRVariable(name="Temperature", iec_type=IECType.REAL, is_input=True),
            ],
        )
        mapping = _make_mapping(
            inputs=[SensorEntry(st_name="Temperature", sensor_name="AI_Temp_S")],
        )
        js = generate(program, mapping)

        assert '{ name: "AI_Temp_S" }' in js


class TestOutputVariableAssignment:
    """Test output variable assignment generates out_SensorName = ..."""

    def test_output_var_ref_uses_out_prefix(self):
        from st2js.codegen import generate

        program = _make_program(
            inputs=[
                IRVariable(name="StartButton", iec_type=IECType.BOOL, is_input=True),
            ],
            outputs=[
                IRVariable(name="Heater", iec_type=IECType.BOOL, is_output=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="Heater"),
                    value=IRVarRef(name="StartButton"),
                ),
            ],
        )
        mapping = _make_mapping(
            inputs=[SensorEntry(st_name="StartButton", sensor_name="DI_Start_S")],
            outputs=[SensorEntry(st_name="Heater", sensor_name="DO_Heater_C")],
        )
        js = generate(program, mapping)

        assert "out_DO_Heater_C = in_DI_Start_S;" in js

    def test_output_sensor_in_uniset_outputs_array(self):
        from st2js.codegen import generate

        program = _make_program(
            outputs=[
                IRVariable(name="Heater", iec_type=IECType.BOOL, is_output=True),
            ],
        )
        mapping = _make_mapping(
            outputs=[SensorEntry(st_name="Heater", sensor_name="DO_Heater_C")],
        )
        js = generate(program, mapping)

        assert '{ name: "DO_Heater_C" }' in js


class TestLocalVariableDeclaration:
    """Test local variable declaration with initial value."""

    def test_local_var_with_initial_value(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="state", iec_type=IECType.INT, initial_value=0, is_local=True),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "let state = 0;" in js

    def test_local_var_without_initial_value(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="counter", iec_type=IECType.INT, is_local=True),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "let counter = 0;" in js

    def test_local_bool_var_default(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="flag", iec_type=IECType.BOOL, is_local=True),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "let flag = false;" in js

    def test_local_real_var_default(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="value", iec_type=IECType.REAL, is_local=True),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "let value = 0.0;" in js

    def test_local_vars_before_on_step(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="state", iec_type=IECType.INT, initial_value=0, is_local=True),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        var_pos = js.index("let state")
        on_step_pos = js.index("function uniset_on_step()")
        assert var_pos < on_step_pos


class TestBinaryOperatorMapping:
    """Test binary operator mapping (especially = -> ===, AND -> &&)."""

    def test_equality_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.INT, is_local=True),
                IRVariable(name="b", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(op="=", left=IRVarRef(name="a"), right=IRVarRef(name="b")),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a === b)" in js

    def test_inequality_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(
                        op="<>",
                        left=IRVarRef(name="a"),
                        right=IRLiteral(value=0, iec_type=IECType.INT),
                    ),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a !== 0)" in js

    def test_and_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="b", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(op="AND", left=IRVarRef(name="a"), right=IRVarRef(name="b")),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a && b)" in js

    def test_or_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(op="OR", left=IRVarRef(name="a"), right=IRLiteral(value=True, iec_type=IECType.BOOL)),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a || true)" in js

    def test_xor_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="b", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(op="XOR", left=IRVarRef(name="a"), right=IRVarRef(name="b")),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a !== b)" in js

    def test_mod_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(
                        op="MOD",
                        left=IRVarRef(name="a"),
                        right=IRLiteral(value=10, iec_type=IECType.INT),
                    ),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a % 10)" in js

    def test_arithmetic_operators_pass_through(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRBinaryOp(
                        op="+",
                        left=IRVarRef(name="a"),
                        right=IRLiteral(value=1, iec_type=IECType.INT),
                    ),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(a + 1)" in js


class TestUnaryOperators:
    """Test unary operator emission."""

    def test_not_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRUnaryOp(op="NOT", operand=IRVarRef(name="a")),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "!a" in js

    def test_negation_operator(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="a", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRUnaryOp(op="-", operand=IRVarRef(name="a")),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "-a" in js


class TestIfElseEmission:
    """Test if/else if/else emission."""

    def test_simple_if(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="flag", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRIfElse(
                    condition=IRVarRef(name="flag"),
                    then_body=[
                        IRAssignment(
                            target=IRVarRef(name="result"),
                            value=IRLiteral(value=1, iec_type=IECType.INT),
                        ),
                    ],
                    elsif_branches=[],
                    else_body=None,
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "if (flag)" in js
        assert "result = 1;" in js

    def test_if_else(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="flag", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRIfElse(
                    condition=IRVarRef(name="flag"),
                    then_body=[
                        IRAssignment(
                            target=IRVarRef(name="result"),
                            value=IRLiteral(value=1, iec_type=IECType.INT),
                        ),
                    ],
                    elsif_branches=[],
                    else_body=[
                        IRAssignment(
                            target=IRVarRef(name="result"),
                            value=IRLiteral(value=0, iec_type=IECType.INT),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "if (flag)" in js
        assert "} else {" in js

    def test_if_elsif_else(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRIfElse(
                    condition=IRBinaryOp(
                        op=">",
                        left=IRVarRef(name="x"),
                        right=IRLiteral(value=10, iec_type=IECType.INT),
                    ),
                    then_body=[
                        IRAssignment(
                            target=IRVarRef(name="result"),
                            value=IRLiteral(value=1, iec_type=IECType.INT),
                        ),
                    ],
                    elsif_branches=[
                        (
                            IRBinaryOp(
                                op=">",
                                left=IRVarRef(name="x"),
                                right=IRLiteral(value=5, iec_type=IECType.INT),
                            ),
                            [
                                IRAssignment(
                                    target=IRVarRef(name="result"),
                                    value=IRLiteral(value=2, iec_type=IECType.INT),
                                ),
                            ],
                        ),
                    ],
                    else_body=[
                        IRAssignment(
                            target=IRVarRef(name="result"),
                            value=IRLiteral(value=3, iec_type=IECType.INT),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "if ((x > 10))" in js
        assert "} else if ((x > 5))" in js
        assert "} else {" in js


class TestTypeCoercion:
    """Test type coercion emission."""

    def test_real_to_int_generates_math_round(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.REAL, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRTypeCoercion(
                        expr=IRVarRef(name="x"),
                        from_type=IECType.REAL,
                        to_type=IECType.INT,
                    ),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "Math.round(x)" in js

    def test_bool_to_int_generates_ternary(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="flag", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="result"),
                    value=IRTypeCoercion(
                        expr=IRVarRef(name="flag"),
                        from_type=IECType.BOOL,
                        to_type=IECType.INT,
                    ),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "(flag ? 1 : 0)" in js


class TestLiterals:
    """Test literal value emission."""

    def test_bool_true(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="x"),
                    value=IRLiteral(value=True, iec_type=IECType.BOOL),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "x = true;" in js

    def test_bool_false(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.BOOL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="x"),
                    value=IRLiteral(value=False, iec_type=IECType.BOOL),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "x = false;" in js

    def test_integer_literal(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="x"),
                    value=IRLiteral(value=42, iec_type=IECType.INT),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "x = 42;" in js

    def test_real_literal(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.REAL, is_local=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="x"),
                    value=IRLiteral(value=3.14, iec_type=IECType.REAL),
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "x = 3.14;" in js


class TestUnmappedVariableWarning:
    """Test that unmapped input/output variables use ST name with warning."""

    def test_unmapped_input_uses_st_name(self):
        from st2js.codegen import generate

        program = _make_program(
            inputs=[
                IRVariable(name="Temperature", iec_type=IECType.REAL, is_input=True),
            ],
            body=[
                IRAssignment(
                    target=IRVarRef(name="Temperature"),
                    value=IRLiteral(value=0.0, iec_type=IECType.REAL),
                ),
            ],
        )
        # No mapping for Temperature
        mapping = _make_mapping()
        js = generate(program, mapping)

        # Should use the ST name directly with in_ prefix
        assert "in_Temperature" in js


class TestIntegrationMinimalPipeline:
    """Integration test: parse minimal.st + mapping -> generate JS."""

    def test_minimal_st_complete_output(self):
        import os
        from st2js.parser import parse_st
        from st2js.transformer import transform
        from st2js.type_system import check_types
        from st2js.codegen import generate
        from st2js.mapping import load_mapping

        fixtures_dir = os.path.join(
            os.path.dirname(__file__), "fixtures"
        )
        st_path = os.path.join(fixtures_dir, "minimal.st")
        mapping_path = os.path.join(fixtures_dir, "minimal_mapping.yaml")

        with open(st_path) as f:
            st_source = f.read()

        parse_result = parse_st(st_source, filename="minimal.st")
        ir_program = transform(parse_result)
        typed_program = check_types(ir_program)
        mapping = load_mapping(mapping_path)

        js = generate(typed_program, mapping)

        # Verify overall structure
        assert '// Generated by st2js from Main' in js
        assert 'load("uniset2-iec61131.js");' in js
        assert 'uniset_inputs' in js
        assert 'uniset_outputs' in js
        assert 'function uniset_on_step()' in js

        # Verify sensor arrays contain correct sensor names
        assert '{ name: "AI_Temp_S" }' in js
        assert '{ name: "DI_Start_S" }' in js
        assert '{ name: "DO_Heater_C" }' in js
        assert '{ name: "AO_Alarm_C" }' in js

        # Verify local variable
        assert 'let state = 0;' in js

        # Verify in_/out_ prefixes in body
        assert 'in_DI_Start_S' in js
        assert 'out_DO_Heater_C' in js

        # Verify if statement generated
        assert 'if (' in js


class TestCaseEmission:
    """Test CASE -> switch/case emission."""

    def test_simple_case(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
                IRVariable(name="y", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRCase(
                    selector=IRVarRef(name="x"),
                    branches=[
                        (
                            [IRLiteral(value=1, iec_type=IECType.INT)],
                            [IRAssignment(
                                target=IRVarRef(name="y"),
                                value=IRLiteral(value=10, iec_type=IECType.INT),
                            )],
                        ),
                        (
                            [IRLiteral(value=2, iec_type=IECType.INT)],
                            [IRAssignment(
                                target=IRVarRef(name="y"),
                                value=IRLiteral(value=20, iec_type=IECType.INT),
                            )],
                        ),
                    ],
                    else_body=None,
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "switch (x)" in js
        assert "case 1:" in js
        assert "case 2:" in js
        assert "y = 10;" in js
        assert "y = 20;" in js
        assert "break;" in js

    def test_case_with_else(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
                IRVariable(name="y", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRCase(
                    selector=IRVarRef(name="x"),
                    branches=[
                        (
                            [IRLiteral(value=1, iec_type=IECType.INT)],
                            [IRAssignment(
                                target=IRVarRef(name="y"),
                                value=IRLiteral(value=10, iec_type=IECType.INT),
                            )],
                        ),
                    ],
                    else_body=[
                        IRAssignment(
                            target=IRVarRef(name="y"),
                            value=IRLiteral(value=0, iec_type=IECType.INT),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "default:" in js
        assert "y = 0;" in js

    def test_case_multiple_match_values(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
                IRVariable(name="y", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRCase(
                    selector=IRVarRef(name="x"),
                    branches=[
                        (
                            [
                                IRLiteral(value=1, iec_type=IECType.INT),
                                IRLiteral(value=2, iec_type=IECType.INT),
                            ],
                            [IRAssignment(
                                target=IRVarRef(name="y"),
                                value=IRLiteral(value=10, iec_type=IECType.INT),
                            )],
                        ),
                    ],
                    else_body=None,
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "case 1:" in js
        assert "case 2:" in js
        assert "y = 10;" in js

    def test_case_each_branch_has_break(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
                IRVariable(name="y", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRCase(
                    selector=IRVarRef(name="x"),
                    branches=[
                        (
                            [IRLiteral(value=1, iec_type=IECType.INT)],
                            [IRAssignment(
                                target=IRVarRef(name="y"),
                                value=IRLiteral(value=10, iec_type=IECType.INT),
                            )],
                        ),
                        (
                            [IRLiteral(value=2, iec_type=IECType.INT)],
                            [IRAssignment(
                                target=IRVarRef(name="y"),
                                value=IRLiteral(value=20, iec_type=IECType.INT),
                            )],
                        ),
                    ],
                    else_body=[
                        IRAssignment(
                            target=IRVarRef(name="y"),
                            value=IRLiteral(value=0, iec_type=IECType.INT),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        # Count break statements: one per branch + one for default
        assert js.count("break;") == 3


class TestForLoopEmission:
    """Test FOR loop -> JS for loop emission."""

    def test_for_with_step(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="i", iec_type=IECType.INT, is_local=True),
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRForLoop(
                    var="i",
                    start=IRLiteral(value=1, iec_type=IECType.INT),
                    end=IRLiteral(value=10, iec_type=IECType.INT),
                    step=IRLiteral(value=2, iec_type=IECType.INT),
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="x"),
                            value=IRBinaryOp(
                                op="+",
                                left=IRVarRef(name="x"),
                                right=IRVarRef(name="i"),
                            ),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "for (let i = 1; i <= 10; i += 2)" in js
        assert "x = (x + i);" in js

    def test_for_without_step_defaults_to_1(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="i", iec_type=IECType.INT, is_local=True),
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRForLoop(
                    var="i",
                    start=IRLiteral(value=0, iec_type=IECType.INT),
                    end=IRLiteral(value=5, iec_type=IECType.INT),
                    step=None,
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="x"),
                            value=IRVarRef(name="i"),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "for (let i = 0; i <= 5; i += 1)" in js

    def test_for_body_indented(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="i", iec_type=IECType.INT, is_local=True),
                IRVariable(name="result", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRForLoop(
                    var="i",
                    start=IRLiteral(value=1, iec_type=IECType.INT),
                    end=IRLiteral(value=10, iec_type=IECType.INT),
                    step=None,
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="result"),
                            value=IRLiteral(value=0, iec_type=IECType.INT),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        # Body assignment inside uniset_on_step should be indented deeper than the for line
        lines = js.split("\n")
        for_line = [l for l in lines if "for (let i" in l][0]
        # Find the "result = 0;" line inside the for body (not the let declaration)
        body_lines = [l for l in lines if "result = 0;" in l and "let" not in l]
        assert len(body_lines) == 1
        body_line = body_lines[0]
        for_indent = len(for_line) - len(for_line.lstrip())
        body_indent = len(body_line) - len(body_line.lstrip())
        assert body_indent > for_indent


class TestWhileLoopEmission:
    """Test WHILE loop -> JS while loop emission."""

    def test_simple_while(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="running", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRWhileLoop(
                    condition=IRVarRef(name="running"),
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="x"),
                            value=IRBinaryOp(
                                op="+",
                                left=IRVarRef(name="x"),
                                right=IRLiteral(value=1, iec_type=IECType.INT),
                            ),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "while (running)" in js
        assert "x = (x + 1);" in js

    def test_while_with_comparison(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRWhileLoop(
                    condition=IRBinaryOp(
                        op=">",
                        left=IRVarRef(name="x"),
                        right=IRLiteral(value=0, iec_type=IECType.INT),
                    ),
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="x"),
                            value=IRBinaryOp(
                                op="-",
                                left=IRVarRef(name="x"),
                                right=IRLiteral(value=1, iec_type=IECType.INT),
                            ),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "while ((x > 0))" in js


class TestRepeatLoopEmission:
    """Test REPEAT..UNTIL -> JS do..while emission."""

    def test_simple_repeat(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRRepeatLoop(
                    condition=IRBinaryOp(
                        op="<=",
                        left=IRVarRef(name="x"),
                        right=IRLiteral(value=0, iec_type=IECType.INT),
                    ),
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="x"),
                            value=IRBinaryOp(
                                op="-",
                                left=IRVarRef(name="x"),
                                right=IRLiteral(value=1, iec_type=IECType.INT),
                            ),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "do {" in js
        assert "} while (!((x <= 0)));" in js
        assert "x = (x - 1);" in js

    def test_repeat_with_variable_condition(self):
        from st2js.codegen import generate

        program = _make_program(
            locals_=[
                IRVariable(name="done", iec_type=IECType.BOOL, is_local=True),
                IRVariable(name="x", iec_type=IECType.INT, is_local=True),
            ],
            body=[
                IRRepeatLoop(
                    condition=IRVarRef(name="done"),
                    body=[
                        IRAssignment(
                            target=IRVarRef(name="x"),
                            value=IRBinaryOp(
                                op="+",
                                left=IRVarRef(name="x"),
                                right=IRLiteral(value=1, iec_type=IECType.INT),
                            ),
                        ),
                    ],
                ),
            ],
        )
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert "do {" in js
        assert "} while (!(done));" in js


class TestLoadDirectives:
    """Tests for load_head / load_on_start emission."""

    def test_load_head_emitted_after_runtime_load(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = SensorMapping(
            inputs=[],
            outputs=[],
            options=MappingOptions(),
            load_head=["helpers/utils.js", "extra.js"],
        )
        js = generate(program, mapping)

        lines = js.splitlines()
        iec_idx = lines.index('load("uniset2-iec61131.js");')
        head1_idx = lines.index('load("helpers/utils.js");')
        head2_idx = lines.index('load("extra.js");')

        assert head1_idx > iec_idx
        assert head2_idx == head1_idx + 1

    def test_load_head_empty_emits_nothing(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = _make_mapping()
        js = generate(program, mapping)

        assert js.count('load("') == 1
        assert 'load("uniset2-iec61131.js");' in js

    def test_load_on_start_emitted_inside_function_body(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = SensorMapping(
            inputs=[],
            outputs=[],
            options=MappingOptions(),
            load_on_start=["sim.js", "post.js"],
        )
        js = generate(program, mapping)

        assert "function uniset_on_start() {\n" in js
        assert '    load("sim.js");' in js
        assert '    load("post.js");' in js
        start_idx = js.index("function uniset_on_start() {")
        close_idx = js.index("}", start_idx)
        body = js[start_idx:close_idx + 1]
        assert body.count("load(") == 2
        assert body.index('load("sim.js")') < body.index('load("post.js")')

    def test_load_on_start_empty_keeps_single_line_stub(self):
        from st2js.codegen import generate

        program = _make_program()
        mapping = _make_mapping()
        js = generate(program, mapping)

        # Regression guard: preserve the current one-liner stub
        assert "function uniset_on_start() {}" in js
