"""End-to-end tests for the st2js converter.

Tests the full pipeline: ST file + YAML mapping -> JavaScript output.
Verifies that the generated JS matches the expected structure from the
Design Doc FR9 format:
  1. load("uniset2-iec61131.js")
  2. uniset_inputs array
  3. uniset_outputs array
  4. Local variable declarations
  5. function uniset_on_step() { ... }

Also tests CLI invocation via subprocess and error cases.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile

import pytest


FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
MINIMAL_ST = os.path.join(FIXTURES_DIR, "minimal.st")
MINIMAL_MAPPING = os.path.join(FIXTURES_DIR, "minimal_mapping.yaml")
CONTROL_FLOW_ST = os.path.join(FIXTURES_DIR, "control_flow.st")
FB_CALLS_ST = os.path.join(FIXTURES_DIR, "fb_calls.st")
FB_CALLS_MAPPING = os.path.join(FIXTURES_DIR, "fb_calls_mapping.yaml")
FB_DECLARATION_ST = os.path.join(FIXTURES_DIR, "fb_declaration.st")
THERMOSTAT_ST = os.path.join(FIXTURES_DIR, "thermostat.st")
THERMOSTAT_MAPPING = os.path.join(FIXTURES_DIR, "thermostat_mapping.yaml")


class TestMinimalPipelineE2E:
    """Full pipeline: minimal.st + minimal_mapping.yaml -> JS output."""

    def _run_pipeline(self) -> str:
        """Run the full pipeline and return JS output string."""
        from st2js.codegen import generate
        from st2js.mapping import load_mapping
        from st2js.parser import parse_st
        from st2js.transformer import transform
        from st2js.type_system import check_types

        with open(MINIMAL_ST) as f:
            st_source = f.read()

        parse_result = parse_st(st_source, filename="minimal.st")
        ir_program = transform(parse_result)
        typed_program = check_types(ir_program)
        mapping = load_mapping(MINIMAL_MAPPING)

        return generate(typed_program, mapping)

    def test_contains_load_statement(self):
        js = self._run_pipeline()
        assert 'load("uniset2-iec61131.js");' in js

    def test_contains_uniset_inputs_array(self):
        js = self._run_pipeline()
        assert "uniset_inputs = [" in js

    def test_contains_uniset_outputs_array(self):
        js = self._run_pipeline()
        assert "uniset_outputs = [" in js

    def test_input_sensors_mapped(self):
        js = self._run_pipeline()
        assert '{ name: "AI_Temp_S" }' in js
        assert '{ name: "DI_Start_S" }' in js

    def test_output_sensors_mapped(self):
        js = self._run_pipeline()
        assert '{ name: "DO_Heater_C" }' in js
        assert '{ name: "AO_Alarm_C" }' in js

    def test_contains_uniset_on_step(self):
        js = self._run_pipeline()
        assert "function uniset_on_step()" in js

    def test_input_variable_substitution(self):
        """VAR_INPUT variables become in_<SensorName>."""
        js = self._run_pipeline()
        assert "in_AI_Temp_S" in js or "in_DI_Start_S" in js

    def test_output_variable_substitution(self):
        """VAR_OUTPUT variables become out_<SensorName>."""
        js = self._run_pipeline()
        assert "out_DO_Heater_C" in js or "out_AO_Alarm_C" in js

    def test_local_variable_declaration(self):
        js = self._run_pipeline()
        assert "let state = 0;" in js

    def test_if_statement_generated(self):
        js = self._run_pipeline()
        assert "if (" in js

    def test_js_structure_order(self):
        """Verify sections appear in correct order: load, inputs, outputs, vars, on_step."""
        js = self._run_pipeline()

        load_pos = js.index('load("uniset2-iec61131.js");')
        inputs_pos = js.index("uniset_inputs")
        outputs_pos = js.index("uniset_outputs")
        vars_pos = js.index("let state")
        on_step_pos = js.index("function uniset_on_step()")

        assert load_pos < inputs_pos < outputs_pos < vars_pos < on_step_pos

    def test_complete_output_snapshot(self):
        """Verify the complete JS output contains all expected elements."""
        js = self._run_pipeline()

        # All required structural elements
        required = [
            '// Generated by st2js from Main',
            'load("uniset2-iec61131.js");',
            "uniset_inputs = [",
            '{ name: "AI_Temp_S" }',
            '{ name: "DI_Start_S" }',
            "uniset_outputs = [",
            '{ name: "DO_Heater_C" }',
            '{ name: "AO_Alarm_C" }',
            "let state = 0;",
            "function uniset_on_step()",
            "in_DI_Start_S",
            "out_DO_Heater_C",
        ]

        for element in required:
            assert element in js, f"Missing expected element: {element!r}"


class TestCLIE2E:
    """End-to-end tests via CLI subprocess."""

    def test_cli_minimal_pipeline(self):
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                MINIMAL_ST,
                "-m", MINIMAL_MAPPING,
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0

        js = result.stdout
        assert 'load("uniset2-iec61131.js");' in js
        assert "uniset_inputs" in js
        assert "uniset_outputs" in js
        assert "function uniset_on_step()" in js
        assert "in_DI_Start_S" in js
        assert "out_DO_Heater_C" in js

    def test_cli_output_to_file(self):
        with tempfile.NamedTemporaryFile(suffix=".js", delete=False) as f:
            outpath = f.name

        try:
            result = subprocess.run(
                [
                    sys.executable, "-m", "st2js",
                    MINIMAL_ST,
                    "-m", MINIMAL_MAPPING,
                    "-o", outpath,
                ],
                capture_output=True,
                text=True,
            )
            assert result.returncode == 0

            with open(outpath) as f:
                js = f.read()

            assert 'load("uniset2-iec61131.js");' in js
            assert "function uniset_on_step()" in js
        finally:
            os.unlink(outpath)

    def test_cli_with_strict_flag(self):
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                MINIMAL_ST,
                "-m", MINIMAL_MAPPING,
                "--strict",
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0

    def test_cli_with_struct_flatten_flag(self):
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                MINIMAL_ST,
                "-m", MINIMAL_MAPPING,
                "--struct-flatten",
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0


class TestErrorCasesE2E:
    """End-to-end error case tests."""

    def test_invalid_st_file_exits_nonzero(self):
        with tempfile.NamedTemporaryFile(
            suffix=".st", mode="w", delete=False
        ) as f:
            f.write("THIS IS NOT VALID ST CODE !!!")
            invalid_st = f.name

        try:
            result = subprocess.run(
                [
                    sys.executable, "-m", "st2js",
                    invalid_st,
                    "-m", MINIMAL_MAPPING,
                ],
                capture_output=True,
                text=True,
            )
            assert result.returncode != 0
            assert result.stderr != ""
        finally:
            os.unlink(invalid_st)

    def test_missing_mapping_file_exits_nonzero(self):
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                MINIMAL_ST,
                "-m", "nonexistent_mapping.yaml",
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode != 0
        assert result.stderr != ""

    def test_missing_input_file_exits_nonzero(self):
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                "nonexistent.st",
                "-m", MINIMAL_MAPPING,
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode != 0
        assert result.stderr != ""

    def test_invalid_st_via_main_function(self):
        """Test error handling directly through main()."""
        from st2js.cli import main

        with tempfile.NamedTemporaryFile(
            suffix=".st", mode="w", delete=False
        ) as f:
            f.write("INVALID { } SYNTAX !!!")
            invalid_st = f.name

        try:
            result = main([invalid_st, "-m", MINIMAL_MAPPING])
            assert result == 1
        finally:
            os.unlink(invalid_st)


class TestControlFlowE2E:
    """E2E tests for control flow constructs (CASE, FOR, WHILE, REPEAT)."""

    def _run_control_flow_pipeline(self) -> str:
        """Run the pipeline on control_flow.st (no mapping needed for locals-only program)."""
        from st2js.codegen import generate
        from st2js.mapping import SensorMapping, MappingOptions
        from st2js.parser import parse_st
        from st2js.transformer import transform
        from st2js.type_system import check_types

        with open(CONTROL_FLOW_ST) as f:
            st_source = f.read()

        parse_result = parse_st(st_source, filename="control_flow.st")
        ir_program = transform(parse_result)
        typed_program = check_types(ir_program)
        mapping = SensorMapping(inputs=[], outputs=[], options=MappingOptions())

        return generate(typed_program, mapping)

    def test_program_structure(self):
        js = self._run_control_flow_pipeline()
        assert 'load("uniset2-iec61131.js");' in js
        assert "function uniset_on_step()" in js

    def test_case_generates_switch(self):
        js = self._run_control_flow_pipeline()
        assert "switch (mystate)" in js
        assert "case 1:" in js
        assert "case 2:" in js
        assert "case 3:" in js
        assert "default:" in js
        assert "break;" in js

    def test_for_generates_for_loop(self):
        js = self._run_control_flow_pipeline()
        assert "for (let i = 1; i <= 10; i += 1)" in js

    def test_while_generates_while_loop(self):
        js = self._run_control_flow_pipeline()
        assert "while (running)" in js

    def test_repeat_generates_do_while(self):
        js = self._run_control_flow_pipeline()
        assert "do {" in js
        assert "while (!(" in js

    def test_local_variable_declarations(self):
        js = self._run_control_flow_pipeline()
        assert "let x = 0;" in js
        assert "let mystate = 1;" in js
        assert "let running = true;" in js

    def test_all_control_flow_types_present(self):
        """Verify all 4 control flow types appear in the generated output."""
        js = self._run_control_flow_pipeline()
        assert "switch (" in js
        assert "for (let " in js
        assert "while (" in js
        assert "do {" in js


class TestFBCallsE2E:
    """E2E tests for function block instantiation and calls."""

    def _run_fb_pipeline(self) -> str:
        """Run the pipeline on fb_calls.st + fb_calls_mapping.yaml."""
        from st2js.codegen import generate
        from st2js.mapping import load_mapping
        from st2js.parser import parse_st
        from st2js.transformer import transform
        from st2js.type_system import check_types

        with open(FB_CALLS_ST) as f:
            st_source = f.read()

        parse_result = parse_st(st_source, filename="fb_calls.st")
        ir_program = transform(parse_result)
        typed_program = check_types(ir_program)
        mapping = load_mapping(FB_CALLS_MAPPING)

        return generate(typed_program, mapping)

    def test_program_structure(self):
        js = self._run_fb_pipeline()
        assert 'load("uniset2-iec61131.js");' in js
        assert "function uniset_on_step()" in js

    def test_fb_instance_declarations(self):
        js = self._run_fb_pipeline()
        assert "const myTimer = new TON(3000);" in js
        assert "const myCounter = new CTU(10);" in js
        assert "const myTrigger = new R_TRIG();" in js
        assert "const myLatch = new RS();" in js

    def test_fb_update_calls(self):
        js = self._run_fb_pipeline()
        assert "myTimer.update(in_DI_Enable_S);" in js
        assert "myCounter.update(in_DI_Pulse_S, in_DI_Reset_S);" in js
        assert "myTrigger.update(in_DI_Enable_S);" in js
        assert "myLatch.update(myTrigger.Q, in_DI_Reset_S);" in js

    def test_fb_output_access(self):
        js = self._run_fb_pipeline()
        assert "out_DO_Output_C = myTimer.Q;" in js
        assert "out_AI_Count_C = myCounter.CV;" in js

    def test_sensor_arrays(self):
        js = self._run_fb_pipeline()
        assert '{ name: "DI_Enable_S" }' in js
        assert '{ name: "DI_Pulse_S" }' in js
        assert '{ name: "DI_Reset_S" }' in js
        assert '{ name: "DO_Output_C" }' in js
        assert '{ name: "AI_Count_C" }' in js

    def test_fb_instances_before_on_step(self):
        js = self._run_fb_pipeline()
        fb_pos = js.index("const myTimer")
        on_step_pos = js.index("function uniset_on_step()")
        assert fb_pos < on_step_pos

    def test_no_local_variables_section(self):
        """FB instances are not local vars, so no 'Local variables' comment needed."""
        js = self._run_fb_pipeline()
        assert "// Local variables" not in js

    def test_cli_fb_calls(self):
        """Test FB calls through CLI subprocess."""
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                FB_CALLS_ST,
                "-m", FB_CALLS_MAPPING,
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0
        js = result.stdout
        assert "new TON(3000)" in js
        assert "myTimer.update(" in js
        assert "myTimer.Q" in js


class TestFBDeclarationE2E:
    """E2E tests for FUNCTION_BLOCK declaration -> JS class."""

    def _run_fb_decl_pipeline(self) -> str:
        """Run the pipeline on fb_declaration.st."""
        from st2js.codegen import generate
        from st2js.mapping import SensorMapping, MappingOptions, SensorEntry
        from st2js.parser import parse_st
        from st2js.transformer import transform
        from st2js.type_system import check_types

        with open(FB_DECLARATION_ST) as f:
            st_source = f.read()

        parse_result = parse_st(st_source, filename="fb_declaration.st")
        ir_program = transform(parse_result)
        typed_program = check_types(ir_program)
        mapping = SensorMapping(
            inputs=[SensorEntry(st_name="Temperature", sensor_name="AI_Temp_S")],
            outputs=[SensorEntry(st_name="Heater", sensor_name="DO_Heater_C")],
            options=MappingOptions(),
        )

        return generate(typed_program, mapping)

    def test_fb_class_generated(self):
        js = self._run_fb_decl_pipeline()
        assert "class MyController {" in js

    def test_fb_constructor(self):
        js = self._run_fb_decl_pipeline()
        assert "constructor()" in js
        assert "this.SetPoint = 0.0;" in js
        assert "this.Enable = false;" in js
        assert "this.Active = false;" in js
        assert "this.counter = 0;" in js

    def test_fb_execute_method(self):
        js = self._run_fb_decl_pipeline()
        assert "execute()" in js
        # Body should use this. prefix for FB variables
        assert "this.counter = (this.counter + 1);" in js

    def test_fb_class_before_on_step(self):
        js = self._run_fb_decl_pipeline()
        class_pos = js.index("class MyController")
        on_step_pos = js.index("function uniset_on_step()")
        assert class_pos < on_step_pos

    def test_program_body_still_works(self):
        js = self._run_fb_decl_pipeline()
        assert "out_DO_Heater_C = true;" in js


class TestThermostatE2E:
    """Full E2E test with a realistic thermostat control program.

    Uses most st2js features: STRUCT, FB instances (TON, R_TRIG, CTU, TOF),
    CASE/IF control flow, scale factors, field access, and sensor mapping.
    """

    def _run_thermostat_pipeline(self) -> str:
        """Run the full pipeline on thermostat.st + thermostat_mapping.yaml."""
        from st2js.codegen import generate
        from st2js.mapping import load_mapping
        from st2js.parser import parse_st
        from st2js.transformer import transform
        from st2js.type_system import check_types

        with open(THERMOSTAT_ST) as f:
            st_source = f.read()

        parse_result = parse_st(st_source, filename="thermostat.st")
        ir_program = transform(parse_result)
        typed_program = check_types(ir_program)
        mapping = load_mapping(THERMOSTAT_MAPPING)

        return generate(typed_program, mapping)

    def test_contains_load_statement(self):
        js = self._run_thermostat_pipeline()
        assert 'load("uniset2-iec61131.js");' in js

    def test_input_sensors_in_uniset_inputs(self):
        js = self._run_thermostat_pipeline()
        assert '{ name: "AI_Temperature_S" }' in js
        assert '{ name: "DI_Enable_S" }' in js
        assert '{ name: "DI_Reset_S" }' in js

    def test_output_sensors_in_uniset_outputs(self):
        js = self._run_thermostat_pipeline()
        assert '{ name: "DO_Heater_C" }' in js
        assert '{ name: "DO_AlarmHigh_C" }' in js
        assert '{ name: "AO_CycleCount_C" }' in js

    def test_scale_factor_for_temperature(self):
        """REAL input with scale: 100 should emit division."""
        js = self._run_thermostat_pipeline()
        assert "in_AI_Temperature_S / 100" in js

    def test_fb_instantiations(self):
        """All declared FBs should be instantiated."""
        js = self._run_thermostat_pipeline()
        assert "const onDelay = new TON(" in js
        assert "const offDelay = new TOF(" in js
        assert "const startEdge = new R_TRIG();" in js
        assert "const cycleCounter = new CTU(" in js

    def test_switch_case_for_state(self):
        """CASE state OF should generate switch/case."""
        js = self._run_thermostat_pipeline()
        assert "switch (state)" in js
        assert "case 0:" in js
        assert "case 1:" in js
        assert "case 2:" in js

    def test_struct_field_access(self):
        """config.setpoint / config.hysteresis / config.maxTemp should appear."""
        js = self._run_thermostat_pipeline()
        assert "config.setpoint" in js
        assert "config.hysteresis" in js
        assert "config.maxTemp" in js

    def test_struct_initial_values(self):
        """STRUCT should be initialized with its default values."""
        js = self._run_thermostat_pipeline()
        assert "let config = { setpoint: 20.0, hysteresis: 2.0, maxTemp: 95.0 };" in js

    def test_fb_update_calls(self):
        """FB calls should emit update() methods."""
        js = self._run_thermostat_pipeline()
        assert "startEdge.update(" in js
        assert "onDelay.update(" in js
        assert "cycleCounter.update(" in js

    def test_fb_output_access(self):
        """FB output access like startEdge.Q, onDelay.Q, cycleCounter.CV."""
        js = self._run_thermostat_pipeline()
        assert "startEdge.Q" in js
        assert "onDelay.Q" in js
        assert "cycleCounter.CV" in js

    def test_program_name_in_comment(self):
        js = self._run_thermostat_pipeline()
        assert "// Generated by st2js from Thermostat" in js

    def test_contains_uniset_on_step(self):
        js = self._run_thermostat_pipeline()
        assert "function uniset_on_step()" in js

    def test_if_else_for_temperature_comparison(self):
        js = self._run_thermostat_pipeline()
        assert "if (" in js
        assert "} else if (" in js

    def test_local_variables(self):
        js = self._run_thermostat_pipeline()
        assert "let state = 0;" in js
        assert "let i = 0;" in js

    def test_js_structure_order(self):
        """Verify sections appear in correct order."""
        js = self._run_thermostat_pipeline()
        load_pos = js.index('load("uniset2-iec61131.js");')
        inputs_pos = js.index("uniset_inputs")
        outputs_pos = js.index("uniset_outputs")
        on_step_pos = js.index("function uniset_on_step()")
        assert load_pos < inputs_pos < outputs_pos < on_step_pos

    def test_cli_thermostat_pipeline(self):
        """Test thermostat through CLI subprocess -- exit code 0."""
        result = subprocess.run(
            [
                sys.executable, "-m", "st2js",
                THERMOSTAT_ST,
                "-m", THERMOSTAT_MAPPING,
            ],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0
        js = result.stdout
        assert 'load("uniset2-iec61131.js");' in js
        assert "switch (state)" in js
        assert "config.setpoint" in js
        assert "in_AI_Temperature_S / 100" in js

    def test_cli_thermostat_output_to_file(self):
        """Test CLI writes thermostat output to file."""
        with tempfile.NamedTemporaryFile(suffix=".js", delete=False) as f:
            outpath = f.name

        try:
            result = subprocess.run(
                [
                    sys.executable, "-m", "st2js",
                    THERMOSTAT_ST,
                    "-m", THERMOSTAT_MAPPING,
                    "-o", outpath,
                ],
                capture_output=True,
                text=True,
            )
            assert result.returncode == 0

            with open(outpath) as f:
                js = f.read()

            assert 'load("uniset2-iec61131.js");' in js
            assert "function uniset_on_step()" in js
            assert "config.setpoint" in js
        finally:
            os.unlink(outpath)


class TestErrorReportingE2E:
    """Tests that error types show correct file:line:col information."""

    def test_parse_error_shows_file_line_col(self):
        """ParseError from invalid ST should include file, line, and column."""
        from st2js.errors import ParseError
        from st2js.parser import parse_st

        invalid_st = "PROGRAM Test\nVAR\n    x : INT;\nEND_VAR\n  @@@ INVALID SYNTAX @@@\nEND_PROGRAM"
        with pytest.raises(ParseError) as exc_info:
            parse_st(invalid_st, filename="bad_program.st")

        err = exc_info.value
        assert err.file == "bad_program.st"
        # The error string should contain the filename
        error_str = str(err)
        assert "bad_program.st" in error_str

    def test_mapping_error_shows_message(self):
        """MappingError for invalid YAML includes descriptive message."""
        from st2js.errors import MappingError
        from st2js.mapping import load_mapping_from_string

        invalid_yaml = """
inputs:
  Temperature:
    no_sensor_field: AI_Temp_S
"""
        with pytest.raises(MappingError) as exc_info:
            load_mapping_from_string(invalid_yaml)

        err = exc_info.value
        error_str = str(err)
        assert "sensor" in error_str.lower()
        assert "Temperature" in error_str

    def test_unsupported_error_shows_file(self):
        """UnsupportedError includes file information."""
        from st2js.errors import UnsupportedError

        err = UnsupportedError(
            "POINTER not supported",
            file="complex.st",
            line=42,
            col=5,
        )
        error_str = str(err)
        assert error_str == "complex.st:42:5: error: POINTER not supported"

    def test_type_error_shows_message(self):
        """STTypeError includes descriptive type information."""
        from st2js.errors import STTypeError

        err = STTypeError(
            "cannot use STRING in arithmetic expression",
            file="types.st",
            line=10,
            col=3,
        )
        error_str = str(err)
        assert error_str == "types.st:10:3: error: cannot use STRING in arithmetic expression"

    def test_cli_parse_error_shows_on_stderr(self):
        """CLI should display parse error on stderr with non-zero exit."""
        with tempfile.NamedTemporaryFile(
            suffix=".st", mode="w", delete=False
        ) as f:
            f.write("PROGRAM Bad\nVAR\n  x : INT;\nEND_VAR\n  @@@ INVALID @@@\nEND_PROGRAM\n")
            bad_st = f.name

        try:
            result = subprocess.run(
                [
                    sys.executable, "-m", "st2js",
                    bad_st,
                    "-m", MINIMAL_MAPPING,
                ],
                capture_output=True,
                text=True,
            )
            assert result.returncode != 0
            assert "st2js:" in result.stderr
            assert "error" in result.stderr.lower()
        finally:
            os.unlink(bad_st)

    def test_cli_mapping_error_shows_on_stderr(self):
        """CLI should display mapping error on stderr for invalid YAML."""
        with tempfile.NamedTemporaryFile(
            suffix=".yaml", mode="w", delete=False
        ) as f:
            f.write("inputs:\n  Temp:\n    no_sensor: wrong\n")
            bad_yaml = f.name

        try:
            result = subprocess.run(
                [
                    sys.executable, "-m", "st2js",
                    MINIMAL_ST,
                    "-m", bad_yaml,
                ],
                capture_output=True,
                text=True,
            )
            assert result.returncode != 0
            assert "st2js:" in result.stderr
            assert "sensor" in result.stderr.lower()
        finally:
            os.unlink(bad_yaml)

    def test_all_error_types_are_sterror_subclasses(self):
        """Verify all error classes inherit from STError for consistent handling."""
        from st2js.errors import (
            STError,
            ParseError,
            STTypeError,
            MappingError,
            UnsupportedError,
        )

        for cls in [ParseError, STTypeError, MappingError, UnsupportedError]:
            assert issubclass(cls, STError), f"{cls.__name__} should inherit from STError"

    def test_all_error_types_format_with_location(self):
        """All error types should format file:line:col when location is provided."""
        from st2js.errors import ParseError, STTypeError, MappingError, UnsupportedError

        for cls in [ParseError, STTypeError, MappingError, UnsupportedError]:
            err = cls("test message", file="test.st", line=5, col=10)
            error_str = str(err)
            assert "test.st:5:10:" in error_str, f"{cls.__name__} should include file:line:col"
            assert "test message" in error_str, f"{cls.__name__} should include message"


class TestLoadDirectivesE2E:
    """End-to-end: load_head/load_on_start through full pipeline + qjsc."""

    def _minimal_st(self, tmp_path):
        import shutil
        st = tmp_path / "min.st"
        shutil.copy(MINIMAL_ST, st)
        return st

    def test_load_directives_emit_correctly_and_syntax_check(self, tmp_path):
        import shutil
        st = self._minimal_st(tmp_path)
        mapping = tmp_path / "map.yaml"
        mapping.write_text(
            "load_head:\n"
            "  - helpers/util.js\n"
            "load_on_start:\n"
            "  - project_sim.js\n"
        )
        out = tmp_path / "out.js"

        from st2js.cli import main
        rc = main([str(st), "-m", str(mapping), "-o", str(out)])
        assert rc == 0

        js = out.read_text()
        assert 'load("uniset2-iec61131.js");' in js
        assert 'load("helpers/util.js");' in js
        # load_on_start lands inside uniset_on_start body
        assert "function uniset_on_start() {\n    load(\"project_sim.js\");\n}" in js

        # qjsc syntax check (skip if qjsc not present on this machine)
        import shutil as _sh
        qjsc = _sh.which("qjsc")
        if qjsc:
            import subprocess
            result = subprocess.run(
                [qjsc, "-c", "-o", "/dev/null", str(out)],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, f"qjsc failed: {result.stderr}"

    def test_cli_flags_override_yaml_absent(self, tmp_path):
        st = self._minimal_st(tmp_path)
        out = tmp_path / "out.js"

        from st2js.cli import main
        rc = main([
            str(st),
            "-o", str(out),
            "--load-head", "a.js",
            "--load-on-start", "b.js",
        ])
        assert rc == 0
        js = out.read_text()
        assert 'load("a.js");' in js
        assert 'load("b.js");' in js

    def test_load_head_skips_core_runtime(self, tmp_path):
        """If user redundantly lists uniset2-iec61131.js, it is not emitted twice."""
        st = self._minimal_st(tmp_path)
        mapping = tmp_path / "map.yaml"
        mapping.write_text(
            "load_head:\n"
            "  - uniset2-iec61131.js\n"
        )
        out = tmp_path / "out.js"

        from st2js.cli import main
        rc = main([str(st), "-m", str(mapping), "-o", str(out)])
        assert rc == 0
        js = out.read_text()
        assert js.count('load("uniset2-iec61131.js");') == 1
