// Generated by st2js from HVAC

// Debug: load visualizer and start HTTP server
try {
    load("uniset2-debug.js");
    if (typeof uniset_debug_set_ui === "function") {
        try { uniset_debug_set_ui(loadFile("uniset2-debug-ui.html")); } catch(e2) {}
    }
    uniset_debug_start(8088);
} catch(e) {
    // uniset2-debug.js not found — debug visualizer unavailable
}

globalThis._program_meta = {
    name: "HVAC",
    inputs: [
        { name: "OutdoorTemp", sensor: "AI_OutdoorTemp_S", type: "REAL", scale: 100 },
        { name: "Zone1Temp", sensor: "AI_Zone1Temp_S", type: "REAL", scale: 100 },
        { name: "Zone2Temp", sensor: "AI_Zone2Temp_S", type: "REAL", scale: 100 },
        { name: "Enable", sensor: "DI_Enable_S", type: "BOOL" },
        { name: "Reset", sensor: "DI_Reset_S", type: "BOOL" },
        { name: "ManualMode", sensor: "DI_ManualMode_S", type: "BOOL" },
    ],
    outputs: [
        { name: "Zone1Heater", sensor: "DO_Zone1Heater_C", type: "BOOL" },
        { name: "Zone2Cooler", sensor: "DO_Zone2Cooler_C", type: "BOOL" },
        { name: "AlarmZone1", sensor: "DO_AlarmZone1_C", type: "BOOL" },
        { name: "AlarmZone2", sensor: "DO_AlarmZone2_C", type: "BOOL" },
        { name: "AlarmCommon", sensor: "DO_AlarmCommon_C", type: "BOOL" },
        { name: "RunHours", sensor: "AO_RunHours_C", type: "INT" },
    ],
    locals: [
        { name: "cfgZone1", type: "STRUCT" },
        { name: "cfgZone2", type: "STRUCT" },
        { name: "state", type: "INT" },
    ],
    globals: [
    ],
    fb_instances: [
        { name: "enableEdge", type: "R_TRIG", inputs: ["CLK"], outputs: ["Q"] },
        { name: "resetEdge", type: "R_TRIG", inputs: ["CLK"], outputs: ["Q"] },
        { name: "z1_hyst", type: "HYSTERESIS", inputs: ["IN", "HIGH", "LOW"], outputs: ["OUT"] },
        { name: "z1_onDelay", type: "TON", inputs: ["IN", "PT"], outputs: ["Q", "ET"] },
        { name: "z1_offDelay", type: "TOF", inputs: ["IN", "PT"], outputs: ["Q", "ET"] },
        { name: "z1_alarmHigh", type: "LIMITALARM", inputs: ["IN", "HIGH", "LOW"], outputs: ["O", "U", "IL"] },
        { name: "z1_cycles", type: "CTU", inputs: ["CU", "RESET", "PV"], outputs: ["Q", "CV"] },
        { name: "z2_hyst", type: "HYSTERESIS", inputs: ["IN", "HIGH", "LOW"], outputs: ["OUT"] },
        { name: "z2_onDelay", type: "TON", inputs: ["IN", "PT"], outputs: ["Q", "ET"] },
        { name: "z2_offDelay", type: "TOF", inputs: ["IN", "PT"], outputs: ["Q", "ET"] },
        { name: "z2_alarmHigh", type: "LIMITALARM", inputs: ["IN", "HIGH", "LOW"], outputs: ["O", "U", "IL"] },
        { name: "z2_cycles", type: "CTU", inputs: ["CU", "RESET", "PV"], outputs: ["Q", "CV"] },
        { name: "blinker", type: "BLINK", inputs: ["ENABLE", "TIMEHIGH", "TIMELOW"], outputs: ["OUT"] },
        { name: "runTimer", type: "TON", inputs: ["IN", "PT"], outputs: ["Q", "ET"] },
        { name: "runCounter", type: "CTU", inputs: ["CU", "RESET", "PV"], outputs: ["Q", "CV"] },
    ],
    operators: [
        { id: "__op1_+", op: "+", inputs: ["IN1", "IN2"] },
        { id: "__op2_-", op: "-", inputs: ["IN1", "IN2"] },
        { id: "__op3_+", op: "+", inputs: ["IN1", "IN2"] },
        { id: "__op4_-", op: "-", inputs: ["IN1", "IN2"] },
        { id: "__op5_NOT", op: "NOT", inputs: ["IN"] },
    ],
    programs: [
        "HVAC",
    ],
    connections: [
        { from: "Enable", to: "enableEdge", toParam: "CLK", kind: "call", program: "HVAC" },
        { from: "Reset", to: "resetEdge", toParam: "CLK", kind: "call", program: "HVAC" },
        { from: "Zone1Temp", to: "z1_hyst", toParam: "IN", kind: "call", program: "HVAC" },
        { from: "cfgZone1", to: "__op1_+", toParam: "IN1", fromField: "setpoint", kind: "call", program: "HVAC" },
        { from: "cfgZone1", to: "__op1_+", toParam: "IN2", fromField: "hysteresis", kind: "call", program: "HVAC" },
        { from: "__op1_+", to: "z1_hyst", toParam: "HIGH", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "cfgZone1", to: "__op2_-", toParam: "IN1", fromField: "setpoint", kind: "call", program: "HVAC" },
        { from: "cfgZone1", to: "__op2_-", toParam: "IN2", fromField: "hysteresis", kind: "call", program: "HVAC" },
        { from: "__op2_-", to: "z1_hyst", toParam: "LOW", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "z1_hyst", to: "z1_onDelay", toParam: "IN", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "z1_onDelay", to: "z1_offDelay", toParam: "IN", fromField: "Q", kind: "call", program: "HVAC" },
        { from: "z1_offDelay", to: "Zone1Heater", toParam: "=", fromField: "Q", kind: "assign", program: "HVAC" },
        { from: "Zone2Temp", to: "z2_hyst", toParam: "IN", kind: "call", program: "HVAC" },
        { from: "cfgZone2", to: "__op3_+", toParam: "IN1", fromField: "setpoint", kind: "call", program: "HVAC" },
        { from: "cfgZone2", to: "__op3_+", toParam: "IN2", fromField: "hysteresis", kind: "call", program: "HVAC" },
        { from: "__op3_+", to: "z2_hyst", toParam: "HIGH", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "cfgZone2", to: "__op4_-", toParam: "IN1", fromField: "setpoint", kind: "call", program: "HVAC" },
        { from: "cfgZone2", to: "__op4_-", toParam: "IN2", fromField: "hysteresis", kind: "call", program: "HVAC" },
        { from: "__op4_-", to: "z2_hyst", toParam: "LOW", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "z2_hyst", to: "__op5_NOT", toParam: "IN", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "__op5_NOT", to: "z2_onDelay", toParam: "IN", fromField: "OUT", kind: "call", program: "HVAC" },
        { from: "z2_onDelay", to: "z2_offDelay", toParam: "IN", fromField: "Q", kind: "call", program: "HVAC" },
        { from: "z2_offDelay", to: "Zone2Cooler", toParam: "=", fromField: "Q", kind: "assign", program: "HVAC" },
        { from: "Zone1Temp", to: "z1_alarmHigh", toParam: "IN", kind: "call", program: "HVAC" },
        { from: "cfgZone1", to: "z1_alarmHigh", toParam: "HIGH", fromField: "alarmHigh", kind: "call", program: "HVAC" },
        { from: "cfgZone1", to: "z1_alarmHigh", toParam: "LOW", fromField: "alarmLow", kind: "call", program: "HVAC" },
        { from: "Zone2Temp", to: "z2_alarmHigh", toParam: "IN", kind: "call", program: "HVAC" },
        { from: "cfgZone2", to: "z2_alarmHigh", toParam: "HIGH", fromField: "alarmHigh", kind: "call", program: "HVAC" },
        { from: "cfgZone2", to: "z2_alarmHigh", toParam: "LOW", fromField: "alarmLow", kind: "call", program: "HVAC" },
        { from: "z1_onDelay", to: "z1_cycles", toParam: "CU", fromField: "Q", kind: "call", program: "HVAC" },
        { from: "Reset", to: "z1_cycles", toParam: "RESET", kind: "call", program: "HVAC" },
        { from: "z2_onDelay", to: "z2_cycles", toParam: "CU", fromField: "Q", kind: "call", program: "HVAC" },
        { from: "Reset", to: "z2_cycles", toParam: "RESET", kind: "call", program: "HVAC" },
        { from: "runTimer", to: "runCounter", toParam: "CU", fromField: "Q", kind: "call", program: "HVAC" },
        { from: "Reset", to: "runCounter", toParam: "RESET", kind: "call", program: "HVAC" },
        { from: "runCounter", to: "RunHours", toParam: "=", fromField: "CV", kind: "assign", program: "HVAC" },
    ],
};

load("uniset2-iec61131.js");
load("uniset2-iec61131-codesys.js");

uniset_inputs = [
    { name: "AI_OutdoorTemp_S" },
    { name: "AI_Zone1Temp_S" },
    { name: "AI_Zone2Temp_S" },
    { name: "DI_Enable_S" },
    { name: "DI_Reset_S" },
    { name: "DI_ManualMode_S" }
];

uniset_outputs = [
    { name: "DO_Zone1Heater_C" },
    { name: "DO_Zone2Cooler_C" },
    { name: "DO_AlarmZone1_C" },
    { name: "DO_AlarmZone2_C" },
    { name: "DO_AlarmCommon_C" },
    { name: "AO_RunHours_C" }
];

// Local variables
let cfgZone1 = { setpoint: 22.0, hysteresis: 1.5, alarmHigh: 35.0, alarmLow: 5.0 };
let cfgZone2 = { setpoint: 22.0, hysteresis: 1.5, alarmHigh: 35.0, alarmLow: 5.0 };
let state = 0;

// Function block instances
const enableEdge = new R_TRIG();
const resetEdge = new R_TRIG();
const z1_hyst = new HYSTERESIS();
const z1_onDelay = new TON(0);
const z1_offDelay = new TOF(0);
const z1_alarmHigh = new LIMITALARM();
const z1_cycles = new CTU(0);
const z2_hyst = new HYSTERESIS();
const z2_onDelay = new TON(0);
const z2_offDelay = new TOF(0);
const z2_alarmHigh = new LIMITALARM();
const z2_cycles = new CTU(0);
const blinker = new BLINK(0, 0);
const runTimer = new TON(0);
const runCounter = new CTU(0);

// Debug: export to globalThis for debug visualizer
globalThis.cfgZone1 = cfgZone1;
globalThis.cfgZone2 = cfgZone2;
globalThis.state = state;
globalThis.enableEdge = enableEdge;
globalThis.resetEdge = resetEdge;
globalThis.z1_hyst = z1_hyst;
globalThis.z1_onDelay = z1_onDelay;
globalThis.z1_offDelay = z1_offDelay;
globalThis.z1_alarmHigh = z1_alarmHigh;
globalThis.z1_cycles = z1_cycles;
globalThis.z2_hyst = z2_hyst;
globalThis.z2_onDelay = z2_onDelay;
globalThis.z2_offDelay = z2_offDelay;
globalThis.z2_alarmHigh = z2_alarmHigh;
globalThis.z2_cycles = z2_cycles;
globalThis.blinker = blinker;
globalThis.runTimer = runTimer;
globalThis.runCounter = runCounter;

function uniset_on_step() {
    let OutdoorTemp = in_AI_OutdoorTemp_S / 100;
    let Zone1Temp = in_AI_Zone1Temp_S / 100;
    let Zone2Temp = in_AI_Zone2Temp_S / 100;
    enableEdge.update(in_DI_Enable_S);
    resetEdge.update(in_DI_Reset_S);
    if (enableEdge.Q) {
        state = 1;
    }
    if (resetEdge.Q) {
        state = 0;
        out_DO_AlarmZone1_C = false;
        out_DO_AlarmZone2_C = false;
        out_DO_AlarmCommon_C = false;
    }
    switch (state) {
        case 0:
            out_DO_Zone1Heater_C = false;
            out_DO_Zone2Cooler_C = false;
            break;
        case 1:
            if (!in_DI_ManualMode_S) {
                z1_hyst.update(Zone1Temp, (cfgZone1.setpoint + cfgZone1.hysteresis), (cfgZone1.setpoint - cfgZone1.hysteresis));
                z1_onDelay.update(z1_hyst.OUT);
                z1_offDelay.update(z1_onDelay.Q);
                out_DO_Zone1Heater_C = z1_offDelay.Q;
                z2_hyst.update(Zone2Temp, (cfgZone2.setpoint + cfgZone2.hysteresis), (cfgZone2.setpoint - cfgZone2.hysteresis));
                z2_onDelay.update(!z2_hyst.OUT);
                z2_offDelay.update(z2_onDelay.Q);
                out_DO_Zone2Cooler_C = z2_offDelay.Q;
            }
            z1_alarmHigh.update(Zone1Temp, cfgZone1.alarmHigh, cfgZone1.alarmLow);
            z2_alarmHigh.update(Zone2Temp, cfgZone2.alarmHigh, cfgZone2.alarmLow);
            out_DO_AlarmZone1_C = !z1_alarmHigh.IL;
            out_DO_AlarmZone2_C = !z2_alarmHigh.IL;
            if ((out_DO_AlarmZone1_C || out_DO_AlarmZone2_C)) {
                out_DO_AlarmCommon_C = true;
                blinker.update(true);
            } else {
                blinker.update(false);
            }
            runTimer.update(true);
            z1_cycles.update(z1_onDelay.Q, in_DI_Reset_S);
            z2_cycles.update(z2_onDelay.Q, in_DI_Reset_S);
            runCounter.update(runTimer.Q, in_DI_Reset_S);
            out_AO_RunHours_C = runCounter.CV;
            break;
        case 2:
            out_DO_Zone1Heater_C = false;
            out_DO_Zone2Cooler_C = false;
            break;
    }
}

function uniset_on_start() {}
function uniset_on_stop() {}
function uniset_process_timers() {}
function uniset_on_sensor() {}
