// Generated by st2js from Thermostat
// Source: thermostat.st + thermostat_mapping.yaml
// Command: python -m st2js thermostat.st -m thermostat_mapping.yaml --debug -o main-plc.js
load("uniset2-debug.js");
uniset_debug_start(8088);
load("main-plc-imitator.js");

// Debug stubs (overridden by uniset2-debug.js when loaded)
if (typeof _dbg_if === 'undefined') {
    globalThis._dbg_if = function(l, c) { return c; };
    globalThis._dbg_case = function(l, v) { return v; };
    globalThis._dbg_begin_cycle = function() {};
    globalThis._dbg_end_cycle = function() {};
}

globalThis._program_meta = {
    name: "Thermostat",
    inputs: [
        { name: "CurrentTemp", sensor: "AI_Temperature_S", type: "REAL", scale: 100 },
        { name: "Enable", sensor: "DI_Enable_S", type: "BOOL" },
        { name: "Reset", sensor: "DI_Reset_S", type: "BOOL" },
    ],
    outputs: [
        { name: "HeaterOn", sensor: "DO_Heater_C", type: "BOOL" },
        { name: "AlarmHigh", sensor: "DO_AlarmHigh_C", type: "BOOL" },
        { name: "CycleCount", sensor: "AO_CycleCount_C", type: "INT" },
    ],
    locals: [
        { name: "config", type: "STRUCT" },
        { name: "state", type: "INT" },
        { name: "i", type: "INT" },
    ],
    fb_instances: [
        { name: "onDelay", type: "TON" },
        { name: "offDelay", type: "TOF" },
        { name: "startEdge", type: "R_TRIG" },
        { name: "cycleCounter", type: "CTU" },
    ],
    connections: [
        { from: "Enable", to: "startEdge", toParam: "CLK", kind: "call" },
        { from: "HeaterOn", to: "onDelay", toParam: "IN", kind: "call" },
        { from: "onDelay", to: "cycleCounter", toParam: "CU", fromField: "Q", kind: "call" },
        { from: "Reset", to: "cycleCounter", toParam: "RESET", kind: "call" },
        { from: "cycleCounter", to: "CycleCount", toParam: "=", fromField: "CV", kind: "assign" },
    ],
};

load("uniset2-iec61131.js");

uniset_inputs = [
    { name: "AI_Temperature_S" },
    { name: "DI_Enable_S" },
    { name: "DI_Reset_S" }
];

uniset_outputs = [
    { name: "DO_Heater_C" },
    { name: "DO_AlarmHigh_C" },
    { name: "AO_CycleCount_C" }
];

// Local variables
let config = { setpoint: 20.0, hysteresis: 2.0, maxTemp: 95.0 };
let state = 0;
let i = 0;

// Function block instances
const onDelay = new TON(0);
const offDelay = new TOF(0);
const startEdge = new R_TRIG();
const cycleCounter = new CTU(0);

// Debug: export to globalThis for debug visualizer
globalThis.config = config;
globalThis.state = state;
globalThis.i = i;
globalThis.onDelay = onDelay;
globalThis.offDelay = offDelay;
globalThis.startEdge = startEdge;
globalThis.cycleCounter = cycleCounter;

function uniset_on_step() {
    _dbg_begin_cycle();
    let CurrentTemp = in_AI_Temperature_S / 100;
    startEdge.update(in_DI_Enable_S);
    if (_dbg_if(81, startEdge.Q)) {
        state = 1;
    }
    switch (_dbg_case(84, state)) {
        case 0:
            out_DO_Heater_C = false;
            break;
        case 1:
            if (_dbg_if(89, (CurrentTemp < (config.setpoint - config.hysteresis)))) {
                out_DO_Heater_C = true;
            } else if (_dbg_if(91, (CurrentTemp > (config.setpoint + config.hysteresis)))) {
                out_DO_Heater_C = false;
            }
            onDelay.update(out_DO_Heater_C);
            cycleCounter.update(onDelay.Q, in_DI_Reset_S);
            out_AO_CycleCount_C = cycleCounter.CV;
            break;
        case 2:
            out_DO_Heater_C = false;
            break;
    }
    if (_dbg_if(102, (CurrentTemp > config.maxTemp))) {
        out_DO_AlarmHigh_C = true;
        state = 2;
    }
    if (_dbg_if(106, in_DI_Reset_S)) {
        state = 0;
        out_DO_AlarmHigh_C = false;
    }
    _dbg_end_cycle();
    imitator.update();
}
