DELETE FROM DigitalSensors WHERE date<=DATE_SUB(NOW(),INTERVAL 10 DAY);
DELETE FROM AnalogSensors WHERE date<=DATE_SUB(NOW(),INTERVAL 10 DAY);
DELETE FROM Messages WHERE date<=DATE_SUB(NOW(),INTERVAL 10 DAY);
DELETE FROM RSChannel WHERE date<=DATE_SUB(NOW(),INTERVAL 10 DAY);
DELETE FROM Network WHERE date<=DATE_SUB(NOW(),INTERVAL 10 DAY);
